package abc.sadnoxx.hashtaggenerator.fragments.hashtag.hashtags

import abc.sadnoxx.hashtaggenerator.R


object CardDataRepository {
    val cardDataList = listOf(
        Card("Most Popular 1", R.string.MPh_1),
        Card("Most Popular 2", R.string.MPh_2),
        Card("Most Popular 3", R.string.MPh_3),
        Card("Most Popular 4", R.string.MPh_4),
        Card("Most Popular 5", R.string.MPh_5),
        Card("Most Popular 6", R.string.MPh_6),
        Card("Most Popular 7", R.string.MPh_7),
        Card("Most Popular 8", R.string.MPh_8),
        Card("Most Popular 9", R.string.MPh_9),
        Card("Most Popular 10", R.string.MPh_10),
        Card("Top Hashtags 1", R.string.Th_1),
        Card("Top Hashtags 2", R.string.Th_2),
        Card("Top Hashtags 3", R.string.Th_3),
        Card("Top Hashtags 4", R.string.Th_4),
        Card("Top Hashtags 5", R.string.Th_5),
        Card("Top Hashtags 6", R.string.Th_6),
        Card("Top Hashtags 7", R.string.Th_7),
        Card("Top Hashtags 8", R.string.Th_8),
        Card("Top Hashtags 9", R.string.Th_9),
        Card("Top Hashtags 10", R.string.Th_10),
        Card("Bath", R.string.activities_bath),
        Card("Biking", R.string.activities_biking),
        Card("Camping", R.string.activities_camping),
        Card("Climb", R.string.activities_Climb),
        Card("Cooking", R.string.activities_cooking),
        Card("Dance", R.string.activities_dance),
        Card("Dressing", R.string.activities_dressing),
        Card("Exercise", R.string.activities_exercise),
        Card("Fishing", R.string.activities_fishing),
        Card("Fitness", R.string.activities_fitness),
        Card("Hiking", R.string.activities_hiking),
        Card("Playing", R.string.activities_Playing),
        Card("Shopping", R.string.activities_shopping),
        Card("Shower", R.string.activities_shower),
        Card("Spa", R.string.activities_spa),
        Card("Sport", R.string.activities_sport),
        Card("Study", R.string.activities_study),
        Card("Swimming", R.string.activities_Swimming),
        Card("Read", R.string.activities_Read),
        Card("Relax", R.string.activities_Relax),
        Card("Run", R.string.activities_Run),
        Card("Watch", R.string.activities_watch),
        Card("Walk", R.string.activities_Walk),
        Card("Work", R.string.activities_work),
        Card("Yoga", R.string.activities_yoga),
        Card("Bird", R.string.Animals_Bird),
        Card("Lion", R.string.Animals_Lion),
        Card("Tiger", R.string.Animals_Tiger),
        Card("Wolf", R.string.Animals_Wolf),
        Card("Fox", R.string.Animals_Fox),
        Card("Eagle", R.string.Animals_Eagle),
        Card("Bull", R.string.Animals_Bull),
        Card("Bear", R.string.Animals_Bear),
        Card("Crocodile", R.string.Animals_Crocodile),
        Card("Whale", R.string.Animals_Whale),
        Card("Snake", R.string.Animals_Snake),
        Card("Shark", R.string.Animals_Shark),
        Card("Pig", R.string.Animals_Pig),
        Card("Elephant", R.string.Animals_Elephant),
        Card("Hippopotamus", R.string.Animals_Hippopotamus),
        Card("Panda", R.string.Animals_Panda),
        Card("Kangaroo", R.string.Animals_Kangaroo),
        Card("Monkey", R.string.Animals_Monkey),
        Card("Vulture", R.string.Animals_Vulture),
        Card("Ostrich", R.string.Animals_Ostrich),
        Card("Antelope", R.string.Animals_Antelope),
        Card("Cat", R.string.Animals_Cat),
        Card("Chicken", R.string.Animals_Chicken),
        Card("Cow", R.string.Animals_Cow),
        Card("Dog", R.string.Animals_Dog),
        Card("Dolphin", R.string.Animals_Dolphin),
        Card("Donkey", R.string.Animals_Donkey),
        Card("Frog", R.string.Animals_Frog),
        Card("Gorilla", R.string.Animals_Gorilla),
        Card("HoneyBee", R.string.Animals_HoneyBee),
        Card("Horse", R.string.Animals_Horse),
        Card("Scorpion", R.string.Animals_Scorpion),
        Card("Turkey", R.string.Animals_Turkey),
        Card("Zebra", R.string.Animals_Zebra),
        Card("Alligator", R.string.Animals_Alligator),
        Card("Butterfly", R.string.Animals_Butterfly),
        Card("Camel", R.string.Animals_Camel),
        Card("Deer", R.string.Animals_Deer),
        Card("Dragonfly", R.string.Animals_Dragonfly),
        Card("Dragon", R.string.Animals_Dragon),
        Card("Giraffe", R.string.Animals_Giraffe),
        Card("Hedgehog", R.string.Animals_Hedgehog),
        Card("Housefly", R.string.Animals_Housefly),
        Card("Leopard Cat", R.string.Animals_LeopardCat),
        Card("Octopus", R.string.Animals_Octopus),
        Card("Penguin", R.string.Animals_Penguin),
        Card("Parrot", R.string.Animals_Parrot),
        Card("Peacock", R.string.Animals_Peacock),
        Card("Pigeon", R.string.Animals_Pigeon),
        Card("Rabbit", R.string.Animals_Rabbit),
        Card("Snail", R.string.Animals_Snail),
        Card("Seagull", R.string.Animals_Seagull),
        Card("Siberian Husky", R.string.Animals_Siberian),
        Card("Spider", R.string.Animals_Spider),
        Card("Starfish", R.string.Animals_Starfish),
        Card("Squirrel", R.string.Animals_Squirrel),
        Card("Abstract Expressionism", R.string.Art_AbstractExpressionism),
        Card("Art Nouveau", R.string.Art_Nouveau),
        Card("Classicism", R.string.Art_Classicism),
        Card("Color Field Painting", R.string.Art_ColorFieldPainting),
        Card("Conceptual Art", R.string.Art_Conceptual),
        Card("Constructivism", R.string.Art_Constructivism),
        Card("Cubism", R.string.Art_Cubism),
        Card("Digital Art", R.string.Art_Digital),
        Card("Expressionism", R.string.Art_Expressionism),
        Card("Fauvism", R.string.Art_Fauvism),
        Card("Futurism", R.string.Art_Futurism),
        Card("Impressionism", R.string.Art_Impressionism),
        Card("Land Art", R.string.Art_Land),
        Card("Minimalism", R.string.Art_Minimalism),
        Card("Neon Art", R.string.Art_Neon),
        Card("Performance", R.string.Art_Performance),
        Card("Pop Art", R.string.Art_Pop),
        Card("Street Art", R.string.Art_Street),
        Card("Symbolism", R.string.Art_Symbolism),
        Card("Portrait", R.string.Art_Portrait),
        Card("Landscape", R.string.Art_Landscape),
        Card("Still Life", R.string.Art_StillLife),
        Card("Abstract", R.string.Art_Abstract),
        Card("Art History", R.string.Art_History),
        Card("Religious Art", R.string.Art_Religious),
        Card("Mannerism", R.string.Art_Mannerism),
        Card("Romanticism", R.string.Art_Romanticism),
        Card("Realism", R.string.Art_Realism),
        Card("Divisionism", R.string.Art_Divisionism),
        Card("Photorealism", R.string.Art_Photorealism),
        Card("Acrylic", R.string.Art_Acrylic),
        Card("Action", R.string.Art_Action),
        Card("Aerial", R.string.Art_Aerial),
        Card("Charcoal", R.string.Art_Charcoal),
        Card("Collage", R.string.Art_Collage),
        Card("Color Pencil", R.string.Art_ColorPencil),
        Card("Encaustic", R.string.Art_Encaustic),
        Card("Foreshortening", R.string.Art_Foreshortening),
        Card("Fresco", R.string.Art_Fresco),
        Card("Glass", R.string.Art_Glass),
        Card("Graffiti", R.string.Art_Graffiti),
        Card("Ink", R.string.Art_Ink),
        Card("Miniature", R.string.Art_Miniature),
        Card("Oil", R.string.Art_Oil),
        Card("Panel", R.string.Art_Panel),
        Card("Panorama", R.string.Art_Panorama),
        Card("Pencil", R.string.Art_Pencil),
        Card("Sand", R.string.Art_Sand),
        Card("Stone", R.string.Art_Stone),
        Card("Watercolor", R.string.Art_Watercolor),
        Card("Handmade", R.string.Art_Handmade),
        Card("Visual", R.string.Art_Visual),
        Card("Plastic", R.string.Art_Plastic),
        Card("Modern", R.string.Art_Modern),
        Card("Contemporary", R.string.Art_Contemporary),
        Card("New Year", R.string.Celebration_NewYear),
        Card("Halloween", R.string.Celebration_halloween),
        Card("Diwali", R.string.Celebration_Diwali),
        Card("Holi", R.string.Celebration_Holi),
        Card("Dussehra", R.string.Celebration_Dussehra),
        Card("Navratri", R.string.Celebration_Navratri),
        Card("Durga Puja", R.string.Celebration_Durga),
        Card("Krishna Janmashtami", R.string.Celebration_KrishnaJanmashtami),
        Card("Ganesh Chaturthi", R.string.Celebration_GaneshChaturthi),
        Card("Gurpurab", R.string.Celebration_Gurpurab),
        Card("Raksha Bandhan", R.string.Celebration_RakshaBandhan),
        Card("Eid ul-Fitr", R.string.Celebration_EidUlFitr),
        Card("Bihu", R.string.Celebration_Bihu),
        Card("Hemis", R.string.Celebration_Hemis),
        Card("Onam", R.string.Celebration_Onam),
        Card("Pongal", R.string.Celebration_Pongal),
        Card("Christmas", R.string.Celebration_Christmas),
        Card("Easter", R.string.Celebration_Easter),
        Card("Baisakhi", R.string.Celebration_Baisakhi),
        Card("Makar Sankranti", R.string.Celebration_MakarSankranti),
        Card("Maha Shivratri", R.string.Celebration_MahaShivratri),
        Card("Basant Panchami", R.string.Celebration_BasantPanchami),
        Card("Mahavir Jayanti", R.string.Celebration_MahavirJayanti),
        Card("Ugadi", R.string.Celebration_Ugadi),
        Card("Chhath Puja", R.string.Celebration_ChhathPuja),
        Card("Govardhan Puja", R.string.Celebration_GovardhanPuja),
        Card("Gudi Padwa", R.string.Celebration_GudiPadwa),
        Card("Republic Day", R.string.Celebration_RepublicDay),
        Card("Camel Festival", R.string.Celebration_CamelFestival),
        Card("Kumbh Mela", R.string.Celebration_KumbhMela),
        Card("Losar", R.string.Celebration_Losar),
        Card("Hornbill Festival", R.string.Celebration_HornbillFestival),
        Card("Mewar Festival", R.string.Celebration_MewarFestival),
        Card("Buddha Jayanti", R.string.Celebration_BuddhaJayanti),
        Card("Thrissur Pooram", R.string.Celebration_ThrissurPooram),
        Card("Ratha Yatra", R.string.Celebration_RathaYatra),
        Card("Independence Day", R.string.Celebration_IndependenceDay),
        Card("Afghanistan", R.string.Countries_Afghanistan),
        Card("Albania", R.string.Countries_Albania),
        Card("Algeria", R.string.Countries_Algeria),
        Card("Andorra", R.string.Countries_Andorra),
        Card("Angola", R.string.Countries_Angola),
        Card("Antigua & Barbuda", R.string.Countries_AntiguaANDBarbuda),
        Card("Argentina", R.string.Countries_Argentina),
        Card("Armenia", R.string.Countries_Armenia),
        Card("Australia", R.string.Countries_Australia),
        Card("Austria", R.string.Countries_Austria),
        Card("Azerbaijan", R.string.Countries_Azerbaijan),
        Card("Bahamas", R.string.Countries_Bahamas),
        Card("Bahrain", R.string.Countries_Bahrain),
        Card("Bangladesh", R.string.Countries_Bangladesh),
        Card("Barbados", R.string.Countries_Barbados),
        Card("Belarus", R.string.Countries_Belarus),
        Card("Belgium", R.string.Countries_Belgium),
        Card("Belize", R.string.Countries_Belize),
        Card("Benin", R.string.Countries_Benin),
        Card("Bhutan", R.string.Countries_Bhutan),
        Card("Bolivia", R.string.Countries_Bolivia),
        Card("Bosnia & Herzegovina", R.string.Countries_BosniaANDHerzegovina),
        Card("Botswana", R.string.Countries_Botswana),
        Card("Brazil", R.string.Countries_Brazil),
        Card("Brunei", R.string.Countries_Brunei),
        Card("Bulgaria", R.string.Countries_Bulgaria),
        Card("Burkina Faso", R.string.Countries_BurkinaFaso),
        Card("Burundi", R.string.Countries_Burundi),
        Card("Cabo Verde", R.string.Countries_CaboVerde),
        Card("Cambodia", R.string.Countries_Cambodia),
        Card("Cameroon", R.string.Countries_Cameroon),
        Card("Canada", R.string.Countries_Canada),
        Card("Central African Republic", R.string.Countries_CentralAfricanRepublic),
        Card("Chad", R.string.Countries_Chad),
        Card("Chile", R.string.Countries_Chile),
        Card("China", R.string.Countries_China),
        Card("Colombia", R.string.Countries_Colombia),
        Card("Comoros", R.string.Countries_Comoros),
        Card("Democratic Republic of Congo", R.string.Countries_DemocraticRepublicCongo),
        Card("Republic of Congo", R.string.Countries_RepublicCongo),
        Card("Costa Rica", R.string.Countries_CostaRica),
        Card("Côte d'Ivoire", R.string.Countries_CôtedIvoire),
        Card("Croatia", R.string.Countries_Croatia),
        Card("Cuba", R.string.Countries_Cuba),
        Card("Cyprus", R.string.Countries_Cyprus),
        Card("Czech Republic", R.string.Countries_CzechRepublic),
        Card("Denmark", R.string.Countries_Denmark),
        Card("Djibouti", R.string.Countries_Djibouti),
        Card("Dominica", R.string.Countries_Dominica),
        Card("Dominican Republic", R.string.Countries_DominicanRepublic),
        Card("East Timor", R.string.Countries_EastTimor),
        Card("Ecuador", R.string.Countries_Ecuador),
        Card("Egypt", R.string.Countries_Egypt),
        Card("El Salvador", R.string.Countries_ElSalvador),
        Card("Equatorial Guinea", R.string.Countries_EquatorialGuinea),
        Card("Eritrea", R.string.Countries_Eritrea),
        Card("Estonia", R.string.Countries_Estonia),
        Card("Eswatini", R.string.Countries_Eswatini),
        Card("Ethiopia", R.string.Countries_Ethiopia),
        Card("Fiji", R.string.Countries_Fiji),
        Card("Finland", R.string.Countries_Finland),
        Card("Eswatini", R.string.Countries_Eswatini),
        Card("Ethiopia", R.string.Countries_Ethiopia),
        Card("Fiji", R.string.Countries_Fiji),
        Card("Finland", R.string.Countries_Finland),
        Card("France", R.string.Countries_France),
        Card("Gabon", R.string.Countries_Gabon),
        Card("Gambia", R.string.Countries_Gambia),
        Card("Georgia", R.string.Countries_Georgia),
        Card("Germany", R.string.Countries_Germany),
        Card("Ghana", R.string.Countries_Ghana),
        Card("Greece", R.string.Countries_Greece),
        Card("Grenada", R.string.Countries_Grenada),
        Card("Guatemala", R.string.Countries_Guatemala),
        Card("Guinea", R.string.Countries_Guinea),
        Card("GuineaBissau", R.string.Countries_GuineaBissau),
        Card("Guyana", R.string.Countries_Guyana),
        Card("Haiti", R.string.Countries_Haiti),
        Card("Honduras", R.string.Countries_Honduras),
        Card("Hungary", R.string.Countries_Hungary),
        Card("Iceland", R.string.Countries_Iceland),
        Card("India", R.string.Countries_India),
        Card("Indonesia", R.string.Countries_Indonesia),
        Card("Iran", R.string.Countries_Iran),
        Card("Iraq", R.string.Countries_Iraq),
        Card("Ireland", R.string.Countries_Ireland),
        Card("Israel", R.string.Countries_Israel),
        Card("Italy", R.string.Countries_Italy),
        Card("Jamaica", R.string.Countries_Jamaica),
        Card("Japan", R.string.Countries_Japan),
        Card("Jordan", R.string.Countries_Jordan),
        Card("Kazakhstan", R.string.Countries_Kazakhstan),
        Card("Kenya", R.string.Countries_Kenya),
        Card("Kiribati", R.string.Countries_Kiribati),
        Card("North Korea", R.string.Countries_KoreaNorth),
        Card("South Korea", R.string.Countries_KoreaSouth),
        Card("Kosovo", R.string.Countries_Kosovo),
        Card("Kuwait", R.string.Countries_Kuwait),
        Card("Kyrgyzstan", R.string.Countries_Kyrgyzstan),
        Card("Laos", R.string.Countries_Laos),
        Card("Latvia", R.string.Countries_Latvia),
        Card("Lebanon", R.string.Countries_Lebanon),
        Card("Lesotho", R.string.Countries_Lesotho),
        Card("Liberia", R.string.Countries_Liberia),
        Card("Libya", R.string.Countries_Libya),
        Card("Liechtenstein", R.string.Countries_Liechtenstein),
        Card("Lithuania", R.string.Countries_Lithuania),
        Card("Luxembourg", R.string.Countries_Luxembourg),
        Card("Madagascar", R.string.Countries_Madagascar),
        Card("Malawi", R.string.Countries_Malawi),
        Card("Malaysia", R.string.Countries_Malaysia),
        Card("Maldives", R.string.Countries_Maldives),
        Card("Mali", R.string.Countries_Mali),
        Card("Malta", R.string.Countries_Malta),
        Card("Marshall Islands", R.string.Countries_MarshallIslands),
        Card("Mauritania", R.string.Countries_Mauritania),
        Card("Mauritius", R.string.Countries_Mauritius),
        Card("Mexico", R.string.Countries_Mexico),
        Card("Micronesia", R.string.Countries_Micronesia),
        Card("Moldova", R.string.Countries_Moldova),
        Card("Monaco", R.string.Countries_Monaco),
        Card("Mongolia", R.string.Countries_Mongolia),
        Card("Montenegro", R.string.Countries_Montenegro),
        Card("Morocco", R.string.Countries_Morocco),
        Card("Mozambique", R.string.Countries_Mozambique),
        Card("Myanmar", R.string.Countries_Myanmar),
        Card("Namibia", R.string.Countries_Namibia),
        Card("Nauru", R.string.Countries_Nauru),
        Card("Nepal", R.string.Countries_Nepal),
        Card("Netherlands", R.string.Countries_Netherlands),
        Card("New Zealand", R.string.Countries_NewZealand),
        Card("Nicaragua", R.string.Countries_Nicaragua),
        Card("Niger", R.string.Countries_Niger),
        Card("Nigeria", R.string.Countries_Nigeria),
        Card("North Macedonia", R.string.Countries_NorthMacedonia),
        Card("Norway", R.string.Countries_Norway),
        Card("Oman", R.string.Countries_Oman),
        Card("Pakistan", R.string.Countries_Pakistan),
        Card("Palau", R.string.Countries_Palau),
        Card("Panama", R.string.Countries_Panama),
        Card("Papua New Guinea", R.string.Countries_PapuaNewGuinea),
        Card("Paraguay", R.string.Countries_Paraguay),
        Card("Peru", R.string.Countries_Peru),
        Card("Philippines", R.string.Countries_Philippines),
        Card("Poland", R.string.Countries_Poland),
        Card("Portugal", R.string.Countries_Portugal),
        Card("Qatar", R.string.Countries_Qatar),
        Card("Romania", R.string.Countries_Romania),
        Card("Russia", R.string.Countries_Russia),
        Card("Rwanda", R.string.Countries_Rwanda),
        Card("Saint Kitts and Nevis", R.string.Countries_SaintKittsNevis),
        Card("Saint Lucia", R.string.Countries_SaintLucia),
        Card("Saint Vincent and the Grenadines", R.string.Countries_SaintVincentGrenadines),
        Card("Samoa", R.string.Countries_Samoa),
        Card("San Marino", R.string.Countries_SanMarino),
        Card("Sao Tome and Principe", R.string.Countries_SaoTomePrincipe),
        Card("Saudi Arabia", R.string.Countries_SaudiArabia),
        Card("Senegal", R.string.Countries_Senegal),
        Card("Serbia", R.string.Countries_Serbia),
        Card("Seychelles", R.string.Countries_Seychelles),
        Card("Sierra Leone", R.string.Countries_SierraLeone),
        Card("Singapore", R.string.Countries_Singapore),
        Card("Slovakia", R.string.Countries_Slovakia),
        Card("Slovenia", R.string.Countries_Slovenia),
        Card("Solomon Islands", R.string.Countries_SolomonIslands),
        Card("Somalia", R.string.Countries_Somalia),
        Card("South Africa", R.string.Countries_SouthAfrica),
        Card("Spain", R.string.Countries_Spain),
        Card("Sri Lanka", R.string.Countries_SriLanka),
        Card("Sudan", R.string.Countries_Sudan),
        Card("South Sudan", R.string.Countries_SudanSouth),
        Card("Suriname", R.string.Countries_Suriname),
        Card("Sweden", R.string.Countries_Sweden),
        Card("Switzerland", R.string.Countries_Switzerland),
        Card("Syria", R.string.Countries_Syria),
        Card("Taiwan", R.string.Countries_Taiwan),
        Card("Tajikistan", R.string.Countries_Tajikistan),
        Card("Tanzania", R.string.Countries_Tanzania),
        Card("Thailand", R.string.Countries_Thailand),
        Card("Togo", R.string.Countries_Togo),
        Card("Tonga", R.string.Countries_Tonga),
        Card("Trinidad and Tobago", R.string.Countries_TrinidadTobago),
        Card("Tunisia", R.string.Countries_Tunisia),
        Card("Turkey", R.string.Countries_Turkey),
        Card("Turkmenistan", R.string.Countries_Turkmenistan),
        Card("Tuvalu", R.string.Countries_Tuvalu),
        Card("Uganda", R.string.Countries_Uganda),
        Card("Ukraine", R.string.Countries_Ukraine),
        Card("United Arab Emirates", R.string.Countries_UnitedArabEmirates),
        Card("United Kingdom", R.string.Countries_UnitedKingdom),
        Card("United States", R.string.Countries_UnitedStates),
        Card("Uruguay", R.string.Countries_Uruguay),
        Card("Uzbekistan", R.string.Countries_Uzbekistan),
        Card("Vanuatu", R.string.Countries_Vanuatu),
        Card("Vatican City", R.string.Countries_VaticanCity),
        Card("Venezuela", R.string.Countries_Venezuela),
        Card("Vietnam", R.string.Countries_Vietnam),
        Card("Yemen", R.string.Countries_Yemen),
        Card("Zambia", R.string.Countries_Zambia),
        Card("Zimbabwe", R.string.Countries_Zimbabwe),
        Card("Water", R.string.Drinks_Water),
        Card("Milk", R.string.Drinks_Milk),
        Card("Tea", R.string.Drinks_Tea),
        Card("Coffee", R.string.Drinks_Coffee),
        Card("Sparkling", R.string.Drinks_Sparkling),
        Card("Juices", R.string.Drinks_Juices),
        Card("Energy", R.string.Drinks_Energy),
        Card("Mocktails", R.string.Drinks_Mocktails),
        Card("Milkshakes", R.string.Drinks_Milkshakes),
        Card("Smoothies", R.string.Drinks_Smoothies),
        Card("Cocoa", R.string.Drinks_Cocoa),
        Card("Tonic", R.string.Drinks_Tonic),
        Card("Beer", R.string.Drinks_Beer),
        Card("Wine", R.string.Drinks_Wine),
        Card("Cider", R.string.Drinks_Cider),
        Card("Cocktails", R.string.Drinks_Cocktails),
        Card("Hard Alcohol", R.string.Drinks_HardAlcohol),
        Card("Bubble Tea", R.string.Drinks_bubbletea),
        Card("Spiked Sodas", R.string.Drinks_Spikedsodas),
        Card("Spirit", R.string.Drinks_spirit),
        Card("Park", R.string.Entertainment_Park),
        Card("Art", R.string.Entertainment_Art),
        Card("Circuses", R.string.Entertainment_Circuses),
        Card("Comedy", R.string.Entertainment_Comedy),
        Card("Event", R.string.Entertainment_Event),
        Card("Dance", R.string.Entertainment_Dance),
        Card("Dinner", R.string.Entertainment_Dinner),
        Card("Fair", R.string.Entertainment_Fair),
        Card("Fashion Show", R.string.Entertainment_FashionShow),
        Card("Festival", R.string.Entertainment_Festival),
        Card("Firework", R.string.Entertainment_Firework),
        Card("Theatre", R.string.Entertainment_Theatre),
        Card("Karaoke", R.string.Entertainment_Karaoke),
        Card("Magic", R.string.Entertainment_Magic),
        Card("Shows", R.string.Entertainment_Shows),
        Card("Media", R.string.Entertainment_Media),
        Card("Movies", R.string.Entertainment_Movies),
        Card("Museums", R.string.Entertainment_Museums),
        Card("Music", R.string.Entertainment_Music),
        Card("Nightclubs", R.string.Entertainment_Nightclubs),
        Card("Operas", R.string.Entertainment_Operas),
        Card("Performance", R.string.Entertainment_Performance),
        Card("Podcast", R.string.Entertainment_Podcast),
        Card("Radio", R.string.Entertainment_Radio),
        Card("Social Media", R.string.Entertainment_SocialMedia),
        Card("Spectator Sports", R.string.Entertainment_SpectatorSports),
        Card("Story", R.string.Entertainment_Story),
        Card("Streaming", R.string.Entertainment_Streaming),
        Card("Television", R.string.Entertainment_Television),
        Card("Trade", R.string.Entertainment_Trade),
        Card("Video", R.string.Entertainment_Video),
        Card("Games", R.string.Entertainment_Games),
        Card("Coding", R.string.Entertainment_coding),
        Card("Zoo", R.string.Entertainment_zoo),
        Card("Circus", R.string.Entertainment_circus),
        Card("Party", R.string.Entertainment_party),
        Card("Drama", R.string.Entertainment_drama),
        Card("Play", R.string.Entertainment_play),
        Card("Toy", R.string.Entertainment_toy),
        Card("Spouse", R.string.Family_Spouse),
        Card("Partner", R.string.Family_partner),
        Card("Children", R.string.Family_Children),
        Card("Parents", R.string.Family_Parents),
        Card("Guardian", R.string.Family_guardian),
        Card("Siblings", R.string.Family_Siblings),
        Card("Grandchildren", R.string.Family_Grandchildren),
        Card("Grandparents", R.string.Family_Grandparents),
        Card("Father", R.string.Family_father),
        Card("Mother", R.string.Family_mother),
        Card("Son", R.string.Family_son),
        Card("Daughter", R.string.Family_daughter),
        Card("Brother", R.string.Family_brother),
        Card("Sister", R.string.Family_sister),
        Card("Husband", R.string.Family_husband),
        Card("Wife", R.string.Family_wife),
        Card("Grandfather", R.string.Family_Grandfather),
        Card("Grandmother", R.string.Family_Grandmother),
        Card("Grandson", R.string.Family_Grandson),
        Card("Granddaughter", R.string.Family_Granddaughter),
        Card("Uncle", R.string.Family_uncle),
        Card("Aunt", R.string.Family_aunt),
        Card("Cousin", R.string.Family_cousin),
        Card("Nephew", R.string.Family_nephew),
        Card("Niece", R.string.Family_niece),
        Card("Stepfather", R.string.Family_stepfather),
        Card("Stepmother", R.string.Family_stepmother),
        Card("Stepson", R.string.Family_stepson),
        Card("Stepdaughter", R.string.Family_stepdaughter),
        Card("Stepsister", R.string.Family_stepsister),
        Card("Stepbrother", R.string.Family_stepbrother),
        Card("Eiffel Tower", R.string.Famous_EiffelTower),
        Card("Great Wall of China", R.string.Famous_GreatWall),
        Card("Kremlin Wall", R.string.Famous_KremlinWall),
        Card("Sphinx", R.string.Famous_Sphinx),
        Card("Taj Mahal", R.string.Famous_Taj),
        Card("Mona Lisa", R.string.Famous_Mona),
        Card("Starry Night", R.string.Famous_Starry),
        Card("Mollywood Actors", R.string.Famous_mollywoodactors),
        Card("Mollywood Actresses", R.string.Famous_mollywoodactress),
        Card("Kollywood Actors", R.string.Famous_kollywoodactors),
        Card("Kollywood Actresses", R.string.Famous_kollywoodactress),
        Card("Bollywood Actors", R.string.Famous_bollywoodactors),
        Card("Bollywood Actresses", R.string.Famous_bollywoodactress),
        Card("Tollywood", R.string.Famous_Tollywood),
        Card("Sandalwood", R.string.Famous_Sandalwood),
        Card("Malayalam", R.string.Famous_malayalam),
        Card("Kerala", R.string.Famous_kerala),
        Card("K-pop Singers", R.string.Famous_kpopsingers),
        Card("Pop Music", R.string.Famous_popmusic),
        Card("Beard", R.string.Fashion_beard),
        Card("Brows", R.string.Fashion_brows),
        Card("Dresses", R.string.Fashion_dresses),
        Card("Eyelashes", R.string.Fashion_eyelashes),
        Card("Hair", R.string.Fashion_hair),
        Card("High Heels", R.string.Fashion_highheels),
        Card("Jewelry", R.string.Fashion_jewerly),
        Card("Lipsticks", R.string.Fashion_lipsticks),
        Card("Makeup", R.string.Fashion_makeup),
        Card("Nails", R.string.Fashion_nails),
        Card("Outfit", R.string.Fashion_outfit),
        Card("Shoes", R.string.Fashion_shoes),
        Card("Tattoos", R.string.Fashion_tattoos),
        Card("Clothes", R.string.Fashion_clothes),
        Card("80s Fashion", R.string.Fashion_80sfashion),
        Card("Designer", R.string.Fashion_designer),
        Card("Blog", R.string.Fashion_blog),
        Card("Mens Fashion", R.string.Fashion_men),
        Card("Fashion House", R.string.Fashion_house),
        Card("Fashion Show", R.string.Fashion_show),
        Card("Fashion Week", R.string.Fashion_week),
        Card("Fashion TV", R.string.Fashion_tv),
        Card("Fashion Dresses", R.string.Fashion_fdresses),
        Card("Mens Fashion", R.string.Fashion_mensfashion),
        Card("Fashion Model", R.string.Fashion_model),
        Card("Fashion Style", R.string.Fashion_style),
        Card("Fashion Magazine", R.string.Fashion_magazine),
        Card("Fashion Korean", R.string.Fashion_korean),
        Card("Mens Fashion", R.string.Fashion_men),
        Card("Fashion New", R.string.Fashion_new),
        Card("Fashion Illustration", R.string.Fashion_illustration),
        Card("Fashion Trends", R.string.Fashion_trends),
        Card("Fashion Women", R.string.Fashion_women),
        Card("Fashion Accessory", R.string.Fashion_accessory),
        Card("Fashion Outfits", R.string.Fashion_outfits),
        Card("Met Gala", R.string.Fashion_metgala),
        Card("Men's Clothing", R.string.Fashion_mensclothing),
        Card("Women's Clothing", R.string.Fashion_womensclothing),
        Card("Hijab Style", R.string.Fashion_stylehijab),
        Card("Homecoming", R.string.Fashion_homecoming),
        Card("Streetwear", R.string.Fashion_streetwear),
        Card("Shein Clothing", R.string.Fashion_sheinclothing),
        Card("90s Fashion", R.string.Fashion_90sfashion),
        Card("Max Fashion", R.string.Fashion_maxfashion),
        Card("Kurta", R.string.Fashion_kurta),
        Card("Vintage Fashion", R.string.Fashion_vintage),
        Card("70s Fashion", R.string.Fashion_70sfashion),
        Card("90s Outfits", R.string.Fashion_90soutfits),
        Card("Men's Wear", R.string.Fashion_menswear),
        Card("Fall Outfits", R.string.Fashion_falloutfits),
        Card("Fast Fashion", R.string.Fashion_fastfashion),
        Card("2000s Fashion", R.string.Fashion_2000sfashion),
        Card("Y2K", R.string.Fashion_y2k),
        Card("Men's Style", R.string.Fashion_mensstyle),
        Card("Shein Men", R.string.Fashion_sheinmen),
        Card("70s Outfits", R.string.Fashion_70soutfits),
        Card("1920s Fashion", R.string.Fashion_1920sfashion),
        Card("Euphoria", R.string.Fashion_euphoria),
        Card("Brands", R.string.Fashion_brands),
        Card("Accessories", R.string.Fashion_accessories),
        Card("Summer", R.string.Fashion_summer),
        Card("Fashionista", R.string.Fashion_fashionista),
        Card("Korean Dress", R.string.Fashion_koreandress),
        Card("Fairy Dress", R.string.Fashion_Fairydress),
        Card("Hoodies", R.string.Fashion_Hoodies),
        Card("Lingerie", R.string.Fashion_Lingerie),
        Card("Shirt", R.string.Fashion_Shirt),
        Card("Sweatshirts", R.string.Fashion_Sweatshirts),
        Card("T-Shirts", R.string.Fashion_Tshirts),
        Card("Hair Clip", R.string.Fashion_Hairclip),
        Card("Wallet", R.string.Fashion_Wallet),
        Card("Bag", R.string.Fashion_Bag),
        Card("Shoes", R.string.Fashion_Shoes),
        Card("Enjoyment", R.string.Feelings_Enjoyment),
        Card("Happiness", R.string.Feelings_happiness),
        Card("Love", R.string.Feelings_love),
        Card("Relief", R.string.Feelings_relief),
        Card("Contentment", R.string.Feelings_contentment),
        Card("Amusement", R.string.Feelings_amusement),
        Card("Joy", R.string.Feelings_joy),
        Card("Pride", R.string.Feelings_pride),
        Card("Excitement", R.string.Feelings_excitement),
        Card("Peace", R.string.Feelings_peace),
        Card("Satisfaction", R.string.Feelings_satisfaction),
        Card("Sadness", R.string.Feelings_Sadness),
        Card("Loneliness", R.string.Feelings_lonely),
        Card("Heartbroken", R.string.Feelings_heartbroken),
        Card("Gloomy", R.string.Feelings_gloomy),
        Card("Disappointed", R.string.Feelings_disappointed),
        Card("Hopeless", R.string.Feelings_hopeless),
        Card("Grieved", R.string.Feelings_grieved),
        Card("Unhappy", R.string.Feelings_unhappy),
        Card("Lost", R.string.Feelings_lost),
        Card("Troubled", R.string.Feelings_troubled),
        Card("Resigned", R.string.Feelings_resigned),
        Card("Miserable", R.string.Feelings_miserable),
        Card("Fear", R.string.Feelings_Fear),
        Card("Worried", R.string.Feelings_worried),
        Card("Doubtful", R.string.Feelings_doubtful),
        Card("Nervous", R.string.Feelings_nervous),
        Card("Anxious", R.string.Feelings_anxious),
        Card("Terrified", R.string.Feelings_terrified),
        Card("Panicked", R.string.Feelings_panicked),
        Card("Horrified", R.string.Feelings_horrified),
        Card("Desperate", R.string.Feelings_desperate),
        Card("Confused", R.string.Feelings_confused),
        Card("Stressed", R.string.Feelings_stressed),
        Card("Anger", R.string.Feelings_Anger),
        Card("Annoyed", R.string.Feelings_annoyed),
        Card("Frustrated", R.string.Feelings_frustrated),
        Card("Peeved", R.string.Feelings_peeved),
        Card("Contrary", R.string.Feelings_contrary),
        Card("Bitter", R.string.Feelings_bitter),
        Card("Irritated", R.string.Feelings_irritated),
        Card("Mad", R.string.Feelings_mad),
        Card("Cheated", R.string.Feelings_cheated),
        Card("Vengeful", R.string.Feelings_vengeful),
        Card("Insulted", R.string.Feelings_insulted),
        Card("Disgust", R.string.Feelings_Disgust),
        Card("Dislike", R.string.Feelings_dislike),
        Card("Loathing", R.string.Feelings_loathing),
        Card("Disapproving", R.string.Feelings_disapproving),
        Card("Offended", R.string.Feelings_offended),
        Card("Uncomfortable", R.string.Feelings_uncomfortable),
        Card("Nauseated", R.string.Feelings_nauseated),
        Card("Disturbed", R.string.Feelings_disturbed),
        Card("Withdrawn", R.string.Feelings_withdrawn),
        Card("Aversion", R.string.Feelings_aversion),
        Card("Apples", R.string.Food_apples),
        Card("Almond", R.string.Food_almond),
        Card("Barley", R.string.Food_barley),
        Card("Bread", R.string.Food_bread),
        Card("Broccoli", R.string.Food_broccoli),
        Card("Cabbage", R.string.Food_Cabbage),
        Card("Cake", R.string.Food_cake),
        Card("Carrots", R.string.Food_carrots),
        Card("Cheese", R.string.Food_cheese),
        Card("Chicken", R.string.Food_chicken),
        Card("Chips", R.string.Food_chips),
        Card("Chocolate", R.string.Food_chocolate),
        Card("Cookies", R.string.Food_cookies),
        Card("Corn", R.string.Food_corn),
        Card("Cupcakes", R.string.Food_cupcakes),
        Card("Crab", R.string.Food_crab),
        Card("Dates", R.string.Food_dates),
        Card("Donuts", R.string.Food_donuts),
        Card("Duck", R.string.Food_duck),
        Card("Eggs", R.string.Food_eggs),
        Card("Fish", R.string.Food_fish),
        Card("Ginger", R.string.Food_ginger),
        Card("Grapes", R.string.Food_grapes),
        Card("Honey", R.string.Food_honey),
        Card("Indian Food", R.string.Food_Indian),
        Card("Milk", R.string.Food_Milk),
        Card("Noodles", R.string.Food_Noodles),
        Card("Pizza", R.string.Food_Pizza),
        Card("Pepperoni", R.string.Food_Pepperoni),
        Card("Spinach", R.string.Food_Spinach),
        Card("Toast", R.string.Food_Toast),
        Card("Bananas", R.string.Food_Bananas),
        Card("Blueberries", R.string.Food_Blueberries),
        Card("Oranges", R.string.Food_Oranges),
        Card("Strawberries", R.string.Food_Strawberries),
        Card("Coconuts", R.string.Food_Coconuts),
        Card("Carrots", R.string.Food_Carrots),
        Card("Cauliflower", R.string.Food_Cauliflower),
        Card("Cucumber", R.string.Food_Cucumber),
        Card("Garlic", R.string.Food_Garlic),
        Card("Onions", R.string.Food_Onions),
        Card("Tomatoes", R.string.Food_Tomatoes),
        Card("Oats", R.string.Food_Oats),
        Card("Grains", R.string.Food_Grains),
        Card("Rice", R.string.Food_rice),
        Card("Legumes", R.string.Food_Legumes),
        Card("Beans", R.string.Food_beans),
        Card("Lentils", R.string.Food_Lentils),
        Card("Peanuts", R.string.Food_Peanuts),
        Card("Yogurt", R.string.Food_Yogurt),
        Card("New Year", R.string.Holidays_NewYear),
        Card("Christmas", R.string.Holidays_christmas),
        Card("Diwali", R.string.Holidays_diwale),
        Card("Easter", R.string.Holidays_easter),
        Card("Halloween", R.string.Holidays_halloween),
        Card("Thanksgiving", R.string.Holidays_thanksgiving),
        Card("Business", R.string.Lifestyle_business),
        Card("College", R.string.Lifestyle_college),
        Card("Health", R.string.Lifestyle_health),
        Card("Motivation", R.string.Lifestyle_motivation),
        Card("School", R.string.Lifestyle_school),
        Card("Work", R.string.Lifestyle_work),
        Card("Beard", R.string.Fashion_beard),
        Card("Brows", R.string.Fashion_brows),
        Card("Dresses", R.string.Fashion_dresses),
        Card("Beach", R.string.Nature_beach),
        Card("Flowers", R.string.Nature_flowers),
        Card("Forest", R.string.Nature_forest),
        Card("Landscape", R.string.Nature_landscape),
        Card("Mountains", R.string.Nature_mountains),
        Card("Sky", R.string.Nature_sky),
        Card("Sunrise", R.string.Nature_sunrise),
        Card("Sunset", R.string.Nature_sunset),
        Card("Earthy", R.string.Nature_Earthy),
        Card("Hilly", R.string.Nature_Hilly),
        Card("Stormy", R.string.Nature_Stormy),
        Card("Misty", R.string.Nature_Misty),
        Card("Tropical", R.string.Nature_Tropical),
        Card("Sunny", R.string.Nature_Sunny),
        Card("Gloomy", R.string.Nature_Gloomy),
        Card("Rainy", R.string.Nature_Rainy),
        Card("Cloudy", R.string.Nature_Cloudy),
        Card("Foggy", R.string.Nature_Foggy),
        Card("Cool", R.string.Nature_Cool),
        Card("Clear", R.string.Nature_Clear),
        Card("Windy", R.string.Nature_Windy),
        Card("Breezy", R.string.Nature_Breezy),
        Card("Wet", R.string.Nature_Wet),
        Card("Fair", R.string.Nature_Fair),
        Card("Mild", R.string.Nature_Mild),
        Card("Mushroom", R.string.Nature_Mushroom),
        Card("Bamboo", R.string.Nature_Bamboo),
        Card("Ivy", R.string.Nature_Ivy),
        Card("Poison Ivy", R.string.Nature_PoisonIvy),
        Card("Tree", R.string.Nature_Tree),
        Card("Garden", R.string.Nature_Garden),
        Card("Bay", R.string.Nature_Bay),
        Card("Lake", R.string.Nature_Lake),
        Card("Sea", R.string.Nature_Sea),
        Card("Ocean", R.string.Nature_Ocean),
        Card("River", R.string.Nature_River),
        Card("Creek", R.string.Nature_Creek),
        Card("Waterfall", R.string.Nature_Waterfall),
        Card("Canyon", R.string.Nature_Canyon),
        Card("Glacier", R.string.Nature_Glacier),
        Card("Meadow", R.string.Nature_Meadow),
        Card("Forest", R.string.Nature_Forest),
        Card("Mountain", R.string.Nature_Mountain),
        Card("Hill", R.string.Nature_Hill),
        Card("Plain", R.string.Nature_Plain),
        Card("Marsh", R.string.Nature_Marsh),
        Card("Island", R.string.Nature_Island),
        Card("Peninsula", R.string.Nature_Peninsula),
        Card("Savanna", R.string.Nature_Savanna),
        Card("Valley", R.string.Nature_Valley),
        Card("Desert", R.string.Nature_Desert),
        Card("Tundra", R.string.Nature_Tundra),
        Card("Cliff", R.string.Nature_Cliff),
        Card("Cave", R.string.Nature_Cave),
        Card("Beach", R.string.Nature_Beach),
        Card("Field", R.string.Nature_Field),
        Card("Erosion", R.string.Nature_Erosion),
        Card("Geyser", R.string.Nature_Geyser),
        Card("Hot Spring", R.string.Nature_HotSpring),
        Card("Seismic", R.string.Nature_Seismic),
        Card("Earthquake", R.string.Nature_Earthquake),
        Card("Volcano", R.string.Nature_Volcano),
        Card("Magma", R.string.Nature_Magma),
        Card("Tsunami", R.string.Nature_Tsunami),
        Card("Atmosphere", R.string.Nature_Atmosphere),
        Card("Ozone", R.string.Nature_Ozone),
        Card("Ecosystems", R.string.Nature_Ecosystems),
        Card("Habitat", R.string.Nature_Habitat),
        Card("Greenhouse", R.string.Nature_Greenhouse),
        Card("Pollutant", R.string.Nature_Pollutant),
        Card("Couple", R.string.People_couple),
        Card("Dating", R.string.People_dating),
        Card("Girls", R.string.People_girls),
        Card("Guys", R.string.People_guys),
        Card("Model", R.string.People_model),
        Card("Selfie", R.string.People_selfie),
        Card("Blog", R.string.Promotion_blog),
        Card("Contest", R.string.Promotion_contest),
        Card("Vines", R.string.Promotion_vines),
        Card("Vlog", R.string.Promotion_vlog),
        Card("Ads", R.string.Promotion_ad),
        Card("Marketing", R.string.Promotion_marketing),
        Card("Brand", R.string.Promotion_brand),
        Card("Advertisements", R.string.Promotion_advertisements),
        Card("Facebook Ad", R.string.Promotion_facebookAd),
        Card("Publicity", R.string.Promotion_publicity),
        Card("Instagram", R.string.SM_instagram),
        Card("Memes", R.string.SM_memes),
        Card("TikTok", R.string.SM_tiktok),
        Card("Triller", R.string.SM_Triller),
        Card("Vimeo", R.string.SM_Vimeo),
        Card("Likee", R.string.SM_Likee),
        Card("Twitter", R.string.SM_Twitter),
        Card("Tumblr", R.string.SM_Tumblr),
        Card("LinkedIn", R.string.SM_LinkedIn),
        Card("WhatsApp", R.string.SM_WhatsApp),
        Card("Snapchat", R.string.SM_Snapchat),
        Card("Pinterest", R.string.SM_Pinterest),
        Card("Reddit", R.string.SM_Reddit),
        Card("YouTube", R.string.SM_YouTube),
        Card("Nextdoor", R.string.SM_Nextdoor),
        Card("Quora", R.string.SM_Quora),
        Card("Twitch", R.string.SM_Twitch),
        Card("Flickr", R.string.SM_Flickr),
        Card("GIPHY", R.string.SM_GIPHY),
        Card("Skype", R.string.SM_Skype),
        Card("Telegram", R.string.SM_Telegram),
        Card("Discord", R.string.SM_Discord),
        Card("StackOverflow", R.string.SM_StackOverflow),
        Card("Clubhouse", R.string.SM_Clubhouse),
        Card("Alpine", R.string.Sports_Alpine),
        Card("Archery", R.string.Sports_Archery),
        Card("Billiards", R.string.Sports_Billiards),
        Card("Bocce", R.string.Sports_Bocce),
        Card("Bodysurfing", R.string.Sports_Bodysurfing),
        Card("Bowling", R.string.Sports_Bowling),
        Card("Canoeing", R.string.Sports_Canoeing),
        Card("Cross Country Skiing", R.string.Sports_Crosscountryskiing),
        Card("Cycling", R.string.Sports_Cycling),
        Card("Dog Sledding", R.string.Sports_Dogsledding),
        Card("Diving", R.string.Sports_Diving),
        Card("Fishing", R.string.Sports_Fishing),
        Card("Fly Fishing", R.string.Sports_Flyfishing),
        Card("Golf", R.string.Sports_Golf),
        Card("Hacky Sack", R.string.Sports_Hackysack),
        Card("Hang Gliding", R.string.Sports_Hanggliding),
        Card("Mountaineering", R.string.Sports_Mountaineering),
        Card("Horse Riding", R.string.Sports_HorseRiding),
        Card("Ice Skating", R.string.Sports_Iceskating),
        Card("Japanese Sword Arts", R.string.Sports_Japaneseswordarts),
        Card("Kayaking", R.string.Sports_Kayaking),
        Card("Kickboxing", R.string.Sports_Kickboxing),
        Card("Motocross Racing", R.string.Sports_Motocrossracing),
        Card("Mountain Biking", R.string.Sports_Mountainbiking),
        Card("Parachuting", R.string.Sports_Parachuting),
        Card("Parasailing", R.string.Sports_Parasailing),
        Card("Pilates", R.string.Sports_Pilates),
        Card("Qigong", R.string.Sports_Qigong),
        Card("Rafting", R.string.Sports_Rafting),
        Card("Rock Climbing", R.string.Sports_Rockclimbing),
        Card("Rollerblading", R.string.Sports_Rollerblading),
        Card("Rope Climbing", R.string.Sports_Ropeclimbing),
        Card("Rope Jumping", R.string.Sports_Ropejumping),
        Card("Rowing", R.string.Sports_Rowing),
        Card("Sailing", R.string.Sports_Sailing),
        Card("Scuba Diving", R.string.Sports_Scuba),
        Card("Diving", R.string.Sports_diving),
        Card("Shuffleboard", R.string.Sports_Shuffleboard),
        Card("Skimboarding", R.string.Sports_Skimboarding),
        Card("Skydiving", R.string.Sports_Skydiving),
        Card("Skysurfing", R.string.Sports_Skysurfing),
        Card("Sledding", R.string.Sports_Sledding),
        Card("Snorkeling", R.string.Sports_Snorkeling),
        Card("Snowboarding", R.string.Sports_Snowboarding),
        Card("Snowmobile Racing", R.string.Sports_Snowmobileracing),
        Card("Snowshoeing", R.string.Sports_Snowshoeing),
        Card("Snow Skiing", R.string.Sports_Snowskiing),
        Card("Speed Skating", R.string.Sports_Speedskating),
        Card("Surfing", R.string.Sports_Surfing),
        Card("Swimming", R.string.Sports_Swimming),
        Card("Tai Chi", R.string.Sports_Taichi),
        Card("Trapeze Artistry", R.string.Sports_Trapezeartistry),
        Card("Triathlon Training", R.string.Sports_Triathlontraining),
        Card("Unicycling", R.string.Sports_Unicycling),
        Card("Wakeboarding", R.string.Sports_Wakeboarding),
        Card("Water Skiing", R.string.Sports_Waterskiing),
        Card("Weightlifting", R.string.Sports_Weightlifting),
        Card("Windsurfing", R.string.Sports_Windsurfing),
        Card("Yoga", R.string.Sports_Yoga),
        Card("Badminton", R.string.Sports_Badminton),
        Card("Basketball", R.string.Sports_Basketball),
        Card("Baseball", R.string.Sports_Baseball),
        Card("Boxing", R.string.Sports_Boxing),
        Card("Broomball", R.string.Sports_Broomball),
        Card("Cheerleading", R.string.Sports_Cheerleading),
        Card("Cricket", R.string.Sports_Cricket),
        Card("Croquet", R.string.Sports_Croquet),
        Card("Curling", R.string.Sports_Curling),
        Card("Fencing", R.string.Sports_Fencing),
        Card("Field Hockey", R.string.Sports_Fieldhockey),
        Card("Flag Football", R.string.Sports_Flagfootball),
        Card("Football", R.string.Sports_Football),
        Card("Handball", R.string.Sports_Handball),
        Card("Hockey", R.string.Sports_Hockey),
        Card("Hurling", R.string.Sports_Hurling),
        Card("Jaialai", R.string.Sports_Jaialai),
        Card("Lacrosse", R.string.Sports_Lacrosse),
        Card("Laser Tag", R.string.Sports_Lasertag),
        Card("Lawn Bowling", R.string.Sports_Lawnbowling),
        Card("Paintball", R.string.Sports_Paintball),
        Card("Racquetball", R.string.Sports_Racquetball),
        Card("Rugby", R.string.Sports_Rugby),
        Card("Soccer", R.string.Sports_Soccer),
        Card("Softball", R.string.Sports_Softball),
        Card("Squash", R.string.Sports_Squash),
        Card("Synchronized Swimming", R.string.Sports_Synchronizedswimming),
        Card("Table Tennis", R.string.Sports_Tabletennis),
        Card("Tennis", R.string.Sports_Tennis),
        Card("Ultimate Frisbee", R.string.Sports_UltimateFrisbee),
        Card("Volleyball", R.string.Sports_Volleyball),
        Card("Wrestling", R.string.Sports_Wrestling),
        Card("Gymnastic Games", R.string.Sports_GymnasticGames),
        Card("Acrobatic Gymnastics", R.string.Sports_AcrobaticGymnastics),
        Card("Balance Beam", R.string.Sports_Balancebeam),
        Card("Floor Exercises", R.string.Sports_Floorexercises),
        Card("High Bar", R.string.Sports_Highbar),
        Card("Parallel Bars", R.string.Sports_Parallelbars),
        Card("Pommel Horse", R.string.Sports_Pommelhorse),
        Card("Rhythmic Gymnastics", R.string.Sports_Rhythmic),
        Card("Still Rings", R.string.Sports_Stillrings),
        Card("Trampoline", R.string.Sports_Trampoline),
        Card("Tumbling", R.string.Sports_Tumbling),
        Card("Uneven Parallel Bars", R.string.Sports_Unevenparallelbars),
        Card("Vault", R.string.Sports_Vault),
        Card("Martial Arts", R.string.Sports_MartialArts),
        Card("Japanese Martial Arts", R.string.Sports_JapaneseMartialArts),
        Card("Aikido", R.string.Sports_Aikido),
        Card("Judo", R.string.Sports_Judo),
        Card("Jujutsu", R.string.Sports_Jujutsu),
        Card("Karate", R.string.Sports_Karate),
        Card("Kendo", R.string.Sports_Kendo),
        Card("Indian Martial Arts", R.string.Sports_IndianMartialArts),
        Card("Dravidian", R.string.Sports_Dravidian),
        Card("Gatka", R.string.Sports_Gatka),
        Card("Kalaripayattu", R.string.Sports_Kalaripayattu),
        Card("Silambam", R.string.Sports_silambam),
        Card("Varmakalai", R.string.Sports_Varmakalai),
        Card("Brazilian Martial Arts", R.string.Sports_BrazilianMartialArts),
        Card("Capoeira", R.string.Sports_Capoeira),
        Card("Brazilian Jiu-Jitsu", R.string.Sports_Brazilianjiujitsu),
        Card("Korean Martial Arts", R.string.Sports_KoreanMartialArts),
        Card("Hapkido", R.string.Sports_Hapkido),
        Card("Taekwondo", R.string.Sports_Taekwondo),
        Card("Chinese Martial Arts", R.string.Sports_ChineseMartialArts),
        Card("Bagua", R.string.Sports_Bagua),
        Card("Drunken Boxing", R.string.Sports_DrunkenBoxing),
        Card("Kung Fu", R.string.Sports_Kungfu),
        Card("Tai Chi Chuan", R.string.Sports_Taichichuan),
        Card("Wing Chun", R.string.Sports_Wingchun),
        Card("Timezone 1", R.string.Timezone_1),
        Card("Timezone 2", R.string.Timezone_2),
        Card("Timezone 3", R.string.Timezone_3),
        Card("Timezone 4", R.string.Timezone_4),
        Card("Timezone 5", R.string.Timezone_5),
        Card("Aircraft", R.string.Transports_aircraft),
        Card("Airplane", R.string.Transports_airplane),
        Card("Ambulance", R.string.Transports_ambulance),
        Card("Auto", R.string.Transports_auto),
        Card("Automobile", R.string.Transports_automobile),
        Card("Bicycle", R.string.Transports_bicycle),
        Card("Boat", R.string.Transports_boat),
        Card("Bus", R.string.Transports_bus),
        Card("Bullet Train", R.string.Transports_bullettrain),
        Card("Battleship", R.string.Transports_battleship),
        Card("Cab", R.string.Transports_cab),
        Card("Car", R.string.Transports_car),
        Card("Cart", R.string.Transports_cart),
        Card("Chopper", R.string.Transports_chopper),
        Card("Coupe", R.string.Transports_coupe),
        Card("Crane", R.string.Transports_crane),
        Card("Cruise Ship", R.string.Transports_cruiseship),
        Card("Cycle", R.string.Transports_cycle),
        Card("Destroyer", R.string.Transports_destroyer),
        Card("Dirt Bike", R.string.Transports_dirtbike),
        Card("Engine", R.string.Transports_engine),
        Card("Fireboat", R.string.Transports_fireboat),
        Card("Glider", R.string.Transports_glider),
        Card("Hybrid", R.string.Transports_hybrid),
        Card("Hydroplane", R.string.Transports_hydroplane),
        Card("Helicopter", R.string.Transports_helicopter),
        Card("Iceboat", R.string.Transports_iceboat),
        Card("Icebreaker", R.string.Transports_icebreaker),
        Card("Jet", R.string.Transports_jet),
        Card("Jetpack", R.string.Transports_jetpack),
        Card("Jumbo Jet", R.string.Transports_jumbojet),
        Card("Jeeps", R.string.Transports_jeep),
        Card("Jet Boats", R.string.Transports_jetboat),
        Card("Lifeboats", R.string.Transports_lifeboat),
        Card("Lorries", R.string.Transports_lorry),
        Card("Motorcars", R.string.Transports_motorcar),
        Card("Motorhomes", R.string.Transports_motorhome),
        Card("Mountain Bikes", R.string.Transports_mountainbike),
        Card("Motorcycles", R.string.Transports_motorcycle),
        Card("Motorboats", R.string.Transports_motorboat),
        Card("Police Cars", R.string.Transports_policecar),
        Card("Pilots", R.string.Transports_pilot),
        Card("Passengers", R.string.Transports_passenger),
        Card("Race Cars", R.string.Transports_racecar),
        Card("Railroads", R.string.Transports_railroad),
        Card("Rickshaws", R.string.Transports_rickshaw),
        Card("Rockets", R.string.Transports_rocket),
        Card("Racing Cars", R.string.Transports_racingcar),
        Card("Satellite", R.string.Transports_satellite),
        Card("Sedan", R.string.Transports_sedan),
        Card("Ship", R.string.Transports_ship),
        Card("Speedboat", R.string.Transports_speedboat),
        Card("Sports Car", R.string.Transports_sportscar),
        Card("SUV", R.string.Transports_SUV),
        Card("Subway", R.string.Transports_subway),
        Card("Submarine", R.string.Transports_submarine),
        Card("Stock Car", R.string.Transports_stockcar),
        Card("Steamboat", R.string.Transports_steamboat),
        Card("Spaceship", R.string.Transports_spaceship),
        Card("Scooter", R.string.Transports_scooter),
        Card("School Bus", R.string.Transports_schoolbus),
        Card("Truck", R.string.Transports_truck),
        Card("Trolley", R.string.Transports_trolley),
        Card("Train", R.string.Transports_train),
        Card("Town Car", R.string.Transports_towncar),
        Card("Taxi", R.string.Transports_taxi),
        Card("Tank", R.string.Transports_tank),
        Card("Van", R.string.Transports_van),
        Card("Vehicle", R.string.Transports_vehicle),
        Card("Wheelchair", R.string.Transports_wheelchair),
        Card("Audi", R.string.Transports_Audi),
        Card("Auburn", R.string.Transports_Auburn),
        Card("Bugatti", R.string.Transports_Bugatti),
        Card("BMW", R.string.Transports_BMW),
        Card("BharatBenz", R.string.Transports_BharatBenz),
        Card("Bentley", R.string.Transports_Bentley),
        Card("Cadillac", R.string.Transports_Cadillac),
        Card("Chevrolet", R.string.Transports_Chevrolet),
        Card("Dodge", R.string.Transports_Dodge),
        Card("Eagle", R.string.Transports_Eagle),
        Card("Eicher", R.string.Transports_Eicher),
        Card("Ferrari", R.string.Transports_Ferrari),
        Card("Fiat", R.string.Transports_Fiat),
        Card("Ford", R.string.Transports_Ford),
        Card("Mustang", R.string.Transports_Mustang),
        Card("Honda", R.string.Transports_Honda),
        Card("Horch", R.string.Transports_Horch),
        Card("Hyundai", R.string.Transports_Hyundai),
        Card("Jaguar", R.string.Transports_Jaguar),
        Card("Kia", R.string.Transports_Kia),
        Card("KTM", R.string.Transports_KTM),
        Card("Lamborghini", R.string.Transports_Lamborghini),
        Card("Land Rover", R.string.Transports_LandRover),
        Card("Lexus Lincoln", R.string.Transports_LexusLincoln),
        Card("Mahindra", R.string.Transports_Mahindra),
        Card("Mercedes-AMG", R.string.Transports_MercedesAMG),
        Card("Mercedes-Benz", R.string.Transports_MercedesBenz),
        Card("Mini", R.string.Transports_Mini),
        Card("Beard", R.string.Fashion_beard),
        Card("Brows", R.string.Fashion_brows),
        Card("Dresses", R.string.Fashion_dresses),
        Card("Mitsubishi", R.string.Transports_Mitsubishi),
        Card("Morgan", R.string.Transports_Morgan),
        Card("Morris", R.string.Transports_Morris),
        Card("NissanGTR", R.string.Transports_NissanGTR),
        Card("Nissan", R.string.Transports_Nissan),
        Card("NissanNismo", R.string.Transports_NissanNismo),
        Card("Pagani", R.string.Transports_Pagani),
        Card("Porsche", R.string.Transports_Porsche),
        Card("Renault", R.string.Transports_Renault),
        Card("RollsRoyce", R.string.Transports_RollsRoyce),
        Card("Tata", R.string.Transports_Tata),
        Card("Tesla", R.string.Transports_Tesla),
        Card("Toyota", R.string.Transports_Toyota),
        Card("Triumph", R.string.Transports_Triumph),
        Card("Volkswagen", R.string.Transports_Volkswagen),
        Card("Volvo", R.string.Transports_Volvo),
        Card("Westfield", R.string.Transports_Westfield),
        Card("Aprilia", R.string.Transports_Aprilia),
        Card("BajajAuto", R.string.Transports_BajajAuto),
        Card("Benelli", R.string.Transports_Benelli),
        Card("Cooper", R.string.Transports_Cooper),
        Card("Ducati", R.string.Transports_Ducati),
        Card("RoyalEnfield", R.string.Transports_RoyalEnfield),
        Card("Suzuki", R.string.Transports_Suzuki),
        Card("Adventure", R.string.Travel_adventure),
        Card("Airtravel", R.string.Travel_Airtravel),
        Card("City", R.string.Travel_city),
        Card("Family", R.string.Travel_family),
        Card("Travel", R.string.Travel_travel),
        Card("Hotels", R.string.Travel_hotels),
        Card("Flights", R.string.Travel_flights),
        Card("Travelocity", R.string.Travel_travelocity),
        Card("Vacation", R.string.Travel_vacation),
        Card("Trip", R.string.Travel_trip),
        Card("Airlines", R.string.Travel_airlines),
        Card("Destination", R.string.Travel_destination),
        Card("Solo", R.string.Travel_solo),
        Card("Tourpackage", R.string.Travel_Tourpackage),
        Card("Airways", R.string.Travel_airways),
        Card("World", R.string.Travel_world),
        Card("Asia", R.string.Travel_asia),
        Card("Tours", R.string.Travel_tours),
        Card("Luxury", R.string.Travel_luxury),
        Card("Holiday", R.string.Travel_holiday),
        Card("Cold", R.string.Season_Cold),
        Card("Cloudy", R.string.Season_Cloudy),
        Card("Humid", R.string.Season_Humid),
        Card("Rainy", R.string.Season_Rainy),
        Card("Sunny", R.string.Season_Sunny),
        Card("Hot", R.string.Season_Hot),
        Card("Windy", R.string.Season_Windy),
        Card("Stormy", R.string.Season_Stormy),
        Card("Hurricanes", R.string.Season_Hurricanes),
        Card("Cyclones", R.string.Season_Cyclones),
        Card("Tornadoes", R.string.Season_Tornadoes),
        Card("Wet", R.string.Season_Wet),
        Card("Dry", R.string.Season_Dry),
        Card("Snow", R.string.Season_Snow),
        Card("Typhoons", R.string.Season_Typhoons),
        Card("Sandstorms", R.string.Season_Sandstorms),
        Card("Snowstorms", R.string.Season_Snowstorms),
        Card("Foggy", R.string.Season_Foggy),
        Card("Thunderstorm", R.string.Season_Thunderstorm),
        Card("Sleet", R.string.Season_Sleet),
        Card("Wildfire", R.string.Season_Wildfire),
        Card("Hail", R.string.Season_Hail),
        Card("Blizzard", R.string.Season_Blizzard),
        Card("Mist", R.string.Season_Mist),
        Card("Avalanche", R.string.Season_Avalanche),
        Card("Spring", R.string.Season_Spring),
        Card("Summer", R.string.Season_Summer),
        Card("Monsoon", R.string.Season_Monsoon),
        Card("Autumn", R.string.Season_Autumn),
        Card("Winter", R.string.Season_Winter),
        Card("Candid", R.string.Candid),
        Card("Candid 1", R.string.Candid1),
        Card("Wedding", R.string.wedding),
        Card("Candid 1", R.string.Candid1),
        Card("Kerala", R.string.kerala),
        Card("Mallu", R.string.mallu),
        Card("Mall", R.string.Mall),
        Card("Goa", R.string.goa),
        Card("Murder", R.string.murder),
        Card("Friends", R.string.friends),
        Card("Mumbai", R.string.mumbai),
        Card("Chennai", R.string.chennai),
        Card("GTA 5", R.string.gta5),
        Card("Minecraft", R.string.Minecraft),
        Card("Freefire", R.string.Freefire),
        Card("Farcry", R.string.Farcry)
    )
}
