package abc.sadnoxx.hashtaggenerator.fragments.hashtag.hashtags

import abc.sadnoxx.hashtaggenerator.R
import abc.sadnoxx.hashtaggenerator.fragments.hashtag.hashtags.Card


object CardDataRepository {
    val cardDataList = listOf(
        Card("Bath", R.string.activities_bath),
        Card("Biking", R.string.activities_biking),
        Card("Camping", R.string.activities_camping),
        Card("Climb", R.string.activities_Climb),
        Card("Cooking", R.string.activities_cooking),
    Card("Dance", R.string.activities_dance),
    Card("Dressing", R.string.activities_dressing),
    Card("Exercise", R.string.activities_exercise),
    Card("Fishing", R.string.activities_fishing),
    Card("Fitness", R.string.activities_fitness),
        Card("Hiking", R.string.activities_hiking),
        Card("Playing", R.string.activities_Playing),
        Card("Shopping", R.string.activities_shopping),
        Card("Shower", R.string.activities_shower),
        Card("Spa", R.string.activities_spa),
        Card("Sport", R.string.activities_sport),
        Card("Study", R.string.activities_study),
        Card("Swimming", R.string.activities_Swimming),
        Card("Read", R.string.activities_Read),
        Card("Relax", R.string.activities_Relax),
        Card("Run", R.string.activities_Run),
        Card("Watch", R.string.activities_watch),
        Card("Walk", R.string.activities_Walk),
        Card("Work", R.string.activities_work),
        Card("Yoga", R.string.activities_yoga),
        Card("Bird", R.string.Animals_Bird),
        Card("Lion", R.string.Animals_Lion),
        Card("Tiger", R.string.Animals_Tiger),
        Card("Wolf", R.string.Animals_Wolf),
        Card("Fox", R.string.Animals_Fox),
        Card("Eagle", R.string.Animals_Eagle),
        Card("Bull", R.string.Animals_Bull),
        Card("Bear", R.string.Animals_Bear),
        Card("Crocodile", R.string.Animals_Crocodile),
        Card("Whale", R.string.Animals_Whale),
        Card("Snake", R.string.Animals_Snake),
        Card("Shark", R.string.Animals_Shark),
        Card("Pig", R.string.Animals_Pig),
        Card("Elephant", R.string.Animals_Elephant),
        Card("Hippopotamus", R.string.Animals_Hippopotamus),
        Card("Panda", R.string.Animals_Panda),
        Card("Kangaroo", R.string.Animals_Kangaroo),
        Card("Monkey", R.string.Animals_Monkey),
        Card("Vulture", R.string.Animals_Vulture),
        Card("Ostrich", R.string.Animals_Ostrich),
        Card("Antelope", R.string.Animals_Antelope),
        Card("Cat", R.string.Animals_Cat),
        Card("Chicken", R.string.Animals_Chicken),
        Card("Cow", R.string.Animals_Cow),
        Card("Dog", R.string.Animals_Dog),
        Card("Dolphin", R.string.Animals_Dolphin),
        Card("Donkey", R.string.Animals_Donkey),
        Card("Frog", R.string.Animals_Frog),
        Card("Gorilla", R.string.Animals_Gorilla),
        Card("HoneyBee", R.string.Animals_HoneyBee),
        Card("Horse", R.string.Animals_Horse),
        Card("Scorpion", R.string.Animals_Scorpion),
        Card("Turkey", R.string.Animals_Turkey),
        Card("Zebra", R.string.Animals_Zebra),
        Card("Alligator", R.string.Animals_Alligator),
        Card("Butterfly", R.string.Animals_Butterfly),
        Card("Camel", R.string.Animals_Camel),
        Card("Deer", R.string.Animals_Deer),
        Card("Dragonfly", R.string.Animals_Dragonfly),
        Card("Dragon", R.string.Animals_Dragon),
        Card("Giraffe", R.string.Animals_Giraffe),
        Card("Hedgehog", R.string.Animals_Hedgehog),
        Card("Housefly", R.string.Animals_Housefly),
        Card("Leopard Cat", R.string.Animals_LeopardCat),
        Card("Octopus", R.string.Animals_Octopus),
        Card("Penguin", R.string.Animals_Penguin),
        Card("Parrot", R.string.Animals_Parrot),
        Card("Peacock", R.string.Animals_Peacock),
        Card("Pigeon", R.string.Animals_Pigeon),
        Card("Rabbit", R.string.Animals_Rabbit),
        Card("Snail", R.string.Animals_Snail),
        Card("Seagull", R.string.Animals_Seagull),
        Card("Siberian Husky", R.string.Animals_Siberian),
        Card("Spider", R.string.Animals_Spider),
        Card("Starfish", R.string.Animals_Starfish),
        Card("Squirrel", R.string.Animals_Squirrel),
        Card("Abstract Expressionism", R.string.Art_AbstractExpressionism),
        Card("Art Nouveau", R.string.Art_Nouveau),
        Card("Classicism", R.string.Art_Classicism),
        Card("Color Field Painting", R.string.Art_ColorFieldPainting),
        Card("Conceptual Art", R.string.Art_Conceptual),
        Card("Constructivism", R.string.Art_Constructivism),
        Card("Cubism", R.string.Art_Cubism),
        Card("Digital Art", R.string.Art_Digital),
        Card("Expressionism", R.string.Art_Expressionism),
        Card("Fauvism", R.string.Art_Fauvism),
        Card("Futurism", R.string.Art_Futurism),
        Card("Impressionism", R.string.Art_Impressionism),
        Card("Land Art", R.string.Art_Land),
        Card("Minimalism", R.string.Art_Minimalism),
        Card("Neon Art", R.string.Art_Neon),
        Card("Performance", R.string.Art_Performance),
        Card("Pop Art", R.string.Art_Pop),
        Card("Street Art", R.string.Art_Street),
        Card("Symbolism", R.string.Art_Symbolism),
        Card("Portrait", R.string.Art_Portrait),
        Card("Landscape", R.string.Art_Landscape),
        Card("Still Life", R.string.Art_StillLife),
        Card("Abstract", R.string.Art_Abstract),
        Card("Art History", R.string.Art_History),
        Card("Religious Art", R.string.Art_Religious),
        Card("Mannerism", R.string.Art_Mannerism),
        Card("Romanticism", R.string.Art_Romanticism),
        Card("Realism", R.string.Art_Realism),
        Card("Divisionism", R.string.Art_Divisionism),
        Card("Photorealism", R.string.Art_Photorealism),
        Card("Acrylic", R.string.Art_Acrylic),
        Card("Action", R.string.Art_Action),
        Card("Aerial", R.string.Art_Aerial),
        Card("Charcoal", R.string.Art_Charcoal),
        Card("Collage", R.string.Art_Collage),
        Card("Color Pencil", R.string.Art_ColorPencil),
        Card("Encaustic", R.string.Art_Encaustic),
        Card("Foreshortening", R.string.Art_Foreshortening),
        Card("Fresco", R.string.Art_Fresco),
        Card("Glass", R.string.Art_Glass),
        Card("Graffiti", R.string.Art_Graffiti),
        Card("Ink", R.string.Art_Ink),
        Card("Miniature", R.string.Art_Miniature),
        Card("Oil", R.string.Art_Oil),
        Card("Panel", R.string.Art_Panel),
        Card("Panorama", R.string.Art_Panorama),
        Card("Pencil", R.string.Art_Pencil),
        Card("Sand", R.string.Art_Sand),
        Card("Stone", R.string.Art_Stone),
        Card("Watercolor", R.string.Art_Watercolor),
        Card("Handmade", R.string.Art_Handmade),
        Card("Visual", R.string.Art_Visual),
        Card("Plastic", R.string.Art_Plastic),
        Card("Modern", R.string.Art_Modern),
        Card("Contemporary", R.string.Art_Contemporary),
        Card("New Year", R.string.Celebration_NewYear),
        Card("Halloween", R.string.Celebration_halloween),
        Card("Diwali", R.string.Celebration_Diwali),
        Card("Holi", R.string.Celebration_Holi),
        Card("Dussehra", R.string.Celebration_Dussehra),
        Card("Navratri", R.string.Celebration_Navratri),
        Card("Durga Puja", R.string.Celebration_Durga),
        Card("Krishna Janmashtami", R.string.Celebration_KrishnaJanmashtami),
        Card("Ganesh Chaturthi", R.string.Celebration_GaneshChaturthi),
        Card("Gurpurab", R.string.Celebration_Gurpurab),
        Card("Raksha Bandhan", R.string.Celebration_RakshaBandhan),
        Card("Eid ul-Fitr", R.string.Celebration_EidUlFitr),
        Card("Bihu", R.string.Celebration_Bihu),
        Card("Hemis", R.string.Celebration_Hemis)









    )
}
