package abc.sadnoxx.hashtaggenerator.fragments.hashtag.hashtags

import abc.sadnoxx.hashtaggenerator.R
import abc.sadnoxx.hashtaggenerator.fragments.hashtag.hashtags.Card


object CardDataRepository {
    val cardDataList = listOf(
        Card("Bath", R.string.activities_bath),
        Card("Biking", R.string.activities_biking),
        Card("Camping", R.string.activities_camping),
        Card("Climb", R.string.activities_Climb),
        Card("Cooking", R.string.activities_cooking),
    Card("Dance", R.string.activities_dance),
    Card("Dressing", R.string.activities_dressing),
    Card("Exercise", R.string.activities_exercise),
    Card("Fishing", R.string.activities_fishing),
    Card("Fitness", R.string.activities_fitness),
        Card("Hiking", R.string.activities_hiking),
        Card("Playing", R.string.activities_Playing),
        Card("Shopping", R.string.activities_shopping),
        Card("Shower", R.string.activities_shower),
        Card("Spa", R.string.activities_spa),
        Card("Sport", R.string.activities_sport),
        Card("Study", R.string.activities_study),
        Card("Swimming", R.string.activities_Swimming),
        Card("Read", R.string.activities_Read),
        Card("Relax", R.string.activities_Relax),
        Card("Run", R.string.activities_Run),
        Card("Watch", R.string.activities_watch),
        Card("Walk", R.string.activities_Walk),
        Card("Work", R.string.activities_work),
        Card("Yoga", R.string.activities_yoga),
        Card("Bird", R.string.Animals_Bird),
        Card("Lion", R.string.Animals_Lion),
        Card("Tiger", R.string.Animals_Tiger),
        Card("Wolf", R.string.Animals_Wolf),
        Card("Fox", R.string.Animals_Fox),
        Card("Eagle", R.string.Animals_Eagle),
        Card("Bull", R.string.Animals_Bull),
        Card("Bear", R.string.Animals_Bear),
        Card("Crocodile", R.string.Animals_Crocodile),
        Card("Whale", R.string.Animals_Whale),
        Card("Snake", R.string.Animals_Snake),
        Card("Shark", R.string.Animals_Shark),
        Card("Pig", R.string.Animals_Pig),
        Card("Elephant", R.string.Animals_Elephant),
        Card("Hippopotamus", R.string.Animals_Hippopotamus),
        Card("Panda", R.string.Animals_Panda),
        Card("Kangaroo", R.string.Animals_Kangaroo),
        Card("Monkey", R.string.Animals_Monkey),
        Card("Vulture", R.string.Animals_Vulture),
        Card("Ostrich", R.string.Animals_Ostrich),
        Card("Antelope", R.string.Animals_Antelope),
        Card("Cat", R.string.Animals_Cat),
        Card("Chicken", R.string.Animals_Chicken),
        Card("Cow", R.string.Animals_Cow),
        Card("Dog", R.string.Animals_Dog),
        Card("Dolphin", R.string.Animals_Dolphin),
        Card("Donkey", R.string.Animals_Donkey),
        Card("Frog", R.string.Animals_Frog),
        Card("Gorilla", R.string.Animals_Gorilla),
        Card("HoneyBee", R.string.Animals_HoneyBee),
        Card("Horse", R.string.Animals_Horse),
        Card("Scorpion", R.string.Animals_Scorpion),
        Card("Turkey", R.string.Animals_Turkey),
        Card("Zebra", R.string.Animals_Zebra),
        Card("Alligator", R.string.Animals_Alligator),
        Card("Butterfly", R.string.Animals_Butterfly),
        Card("Camel", R.string.Animals_Camel),
        Card("Deer", R.string.Animals_Deer),
        Card("Dragonfly", R.string.Animals_Dragonfly),
        Card("Dragon", R.string.Animals_Dragon),
        Card("Giraffe", R.string.Animals_Giraffe),
        Card("Hedgehog", R.string.Animals_Hedgehog),
        Card("Housefly", R.string.Animals_Housefly),
        Card("Leopard Cat", R.string.Animals_LeopardCat),
        Card("Octopus", R.string.Animals_Octopus),
        Card("Penguin", R.string.Animals_Penguin),
        Card("Parrot", R.string.Animals_Parrot),
        Card("Peacock", R.string.Animals_Peacock),
        Card("Pigeon", R.string.Animals_Pigeon),
        Card("Rabbit", R.string.Animals_Rabbit),
        Card("Snail", R.string.Animals_Snail),
        Card("Seagull", R.string.Animals_Seagull),
        Card("Siberian Husky", R.string.Animals_Siberian),
        Card("Spider", R.string.Animals_Spider),
        Card("Starfish", R.string.Animals_Starfish),
        Card("Squirrel", R.string.Animals_Squirrel),
        Card("Abstract Expressionism", R.string.Art_AbstractExpressionism),
        Card("Art Nouveau", R.string.Art_Nouveau),
        Card("Classicism", R.string.Art_Classicism),
        Card("Color Field Painting", R.string.Art_ColorFieldPainting),
        Card("Conceptual Art", R.string.Art_Conceptual),
        Card("Constructivism", R.string.Art_Constructivism),
        Card("Cubism", R.string.Art_Cubism),
        Card("Digital Art", R.string.Art_Digital),
        Card("Expressionism", R.string.Art_Expressionism),
        Card("Fauvism", R.string.Art_Fauvism),
        Card("Futurism", R.string.Art_Futurism),
        Card("Impressionism", R.string.Art_Impressionism),
        Card("Land Art", R.string.Art_Land),
        Card("Minimalism", R.string.Art_Minimalism),
        Card("Neon Art", R.string.Art_Neon),
        Card("Performance", R.string.Art_Performance),
        Card("Pop Art", R.string.Art_Pop),
        Card("Street Art", R.string.Art_Street),
        Card("Symbolism", R.string.Art_Symbolism),
        Card("Portrait", R.string.Art_Portrait),
        Card("Landscape", R.string.Art_Landscape),
        Card("Still Life", R.string.Art_StillLife),
        Card("Abstract", R.string.Art_Abstract),
        Card("Art History", R.string.Art_History),
        Card("Religious Art", R.string.Art_Religious),
        Card("Mannerism", R.string.Art_Mannerism),
        Card("Romanticism", R.string.Art_Romanticism),
        Card("Realism", R.string.Art_Realism),
        Card("Divisionism", R.string.Art_Divisionism),
        Card("Photorealism", R.string.Art_Photorealism),
        Card("Acrylic", R.string.Art_Acrylic),
        Card("Action", R.string.Art_Action),
        Card("Aerial", R.string.Art_Aerial),
        Card("Charcoal", R.string.Art_Charcoal),
        Card("Collage", R.string.Art_Collage),
        Card("Color Pencil", R.string.Art_ColorPencil),
        Card("Encaustic", R.string.Art_Encaustic),
        Card("Foreshortening", R.string.Art_Foreshortening),
        Card("Fresco", R.string.Art_Fresco),
        Card("Glass", R.string.Art_Glass),
        Card("Graffiti", R.string.Art_Graffiti),
        Card("Ink", R.string.Art_Ink),
        Card("Miniature", R.string.Art_Miniature),
        Card("Oil", R.string.Art_Oil),
        Card("Panel", R.string.Art_Panel),
        Card("Panorama", R.string.Art_Panorama),
        Card("Pencil", R.string.Art_Pencil),
        Card("Sand", R.string.Art_Sand),
        Card("Stone", R.string.Art_Stone),
        Card("Watercolor", R.string.Art_Watercolor),
        Card("Handmade", R.string.Art_Handmade),
        Card("Visual", R.string.Art_Visual),
        Card("Plastic", R.string.Art_Plastic),
        Card("Modern", R.string.Art_Modern),
        Card("Contemporary", R.string.Art_Contemporary),
        Card("New Year", R.string.Celebration_NewYear),
        Card("Halloween", R.string.Celebration_halloween),
        Card("Diwali", R.string.Celebration_Diwali),
        Card("Holi", R.string.Celebration_Holi),
        Card("Dussehra", R.string.Celebration_Dussehra),
        Card("Navratri", R.string.Celebration_Navratri),
        Card("Durga Puja", R.string.Celebration_Durga),
        Card("Krishna Janmashtami", R.string.Celebration_KrishnaJanmashtami),
        Card("Ganesh Chaturthi", R.string.Celebration_GaneshChaturthi),
        Card("Gurpurab", R.string.Celebration_Gurpurab),
        Card("Raksha Bandhan", R.string.Celebration_RakshaBandhan),
        Card("Eid ul-Fitr", R.string.Celebration_EidUlFitr),
        Card("Bihu", R.string.Celebration_Bihu),
        Card("Hemis", R.string.Celebration_Hemis),
        Card("Onam", R.string.Celebration_Onam),
        Card("Pongal", R.string.Celebration_Pongal),
        Card("Christmas", R.string.Celebration_Christmas),
        Card("Easter", R.string.Celebration_Easter),
        Card("Baisakhi", R.string.Celebration_Baisakhi),
        Card("Makar Sankranti", R.string.Celebration_MakarSankranti),
        Card("Maha Shivratri", R.string.Celebration_MahaShivratri),
        Card("Basant Panchami", R.string.Celebration_BasantPanchami),
        Card("Mahavir Jayanti", R.string.Celebration_MahavirJayanti),
        Card("Ugadi", R.string.Celebration_Ugadi),
        Card("Chhath Puja", R.string.Celebration_ChhathPuja),
        Card("Govardhan Puja", R.string.Celebration_GovardhanPuja),
        Card("Gudi Padwa", R.string.Celebration_GudiPadwa),
        Card("Republic Day", R.string.Celebration_RepublicDay),
        Card("Camel Festival", R.string.Celebration_CamelFestival),
        Card("Kumbh Mela", R.string.Celebration_KumbhMela),
        Card("Losar", R.string.Celebration_Losar),
        Card("Hornbill Festival", R.string.Celebration_HornbillFestival),
        Card("Mewar Festival", R.string.Celebration_MewarFestival),
        Card("Buddha Jayanti", R.string.Celebration_BuddhaJayanti),
        Card("Thrissur Pooram", R.string.Celebration_ThrissurPooram),
        Card("Ratha Yatra", R.string.Celebration_RathaYatra),
        Card("Independence Day", R.string.Celebration_IndependenceDay),
        Card("Afghanistan", R.string.Countries_Afghanistan),
        Card("Albania", R.string.Countries_Albania),
        Card("Algeria", R.string.Countries_Algeria),
        Card("Andorra", R.string.Countries_Andorra),
        Card("Angola", R.string.Countries_Angola),
        Card("Antigua & Barbuda", R.string.Countries_AntiguaANDBarbuda),
        Card("Argentina", R.string.Countries_Argentina),
        Card("Armenia", R.string.Countries_Armenia),
        Card("Australia", R.string.Countries_Australia),
        Card("Austria", R.string.Countries_Austria),Card("Azerbaijan", R.string.Countries_Azerbaijan),
        Card("Bahamas", R.string.Countries_Bahamas),
        Card("Bahrain", R.string.Countries_Bahrain),
        Card("Bangladesh", R.string.Countries_Bangladesh),
        Card("Barbados", R.string.Countries_Barbados),
        Card("Belarus", R.string.Countries_Belarus),
        Card("Belgium", R.string.Countries_Belgium),
        Card("Belize", R.string.Countries_Belize),
        Card("Benin", R.string.Countries_Benin),
        Card("Bhutan", R.string.Countries_Bhutan),
        Card("Bolivia", R.string.Countries_Bolivia),
        Card("Bosnia & Herzegovina", R.string.Countries_BosniaANDHerzegovina),
        Card("Botswana", R.string.Countries_Botswana),
        Card("Brazil", R.string.Countries_Brazil),
        Card("Brunei", R.string.Countries_Brunei),
        Card("Bulgaria", R.string.Countries_Bulgaria),
        Card("Burkina Faso", R.string.Countries_BurkinaFaso),
        Card("Burundi", R.string.Countries_Burundi),
        Card("Cabo Verde", R.string.Countries_CaboVerde),
        Card("Cambodia", R.string.Countries_Cambodia),
        Card("Cameroon", R.string.Countries_Cameroon),
        Card("Canada", R.string.Countries_Canada),
        Card("Central African Republic", R.string.Countries_CentralAfricanRepublic),
        Card("Chad", R.string.Countries_Chad),
        Card("Chile", R.string.Countries_Chile),
        Card("China", R.string.Countries_China),Card("Colombia", R.string.Countries_Colombia),
        Card("Comoros", R.string.Countries_Comoros),
        Card("Democratic Republic of Congo", R.string.Countries_DemocraticRepublicCongo),
        Card("Republic of Congo", R.string.Countries_RepublicCongo),
        Card("Costa Rica", R.string.Countries_CostaRica),
        Card("Côte d'Ivoire", R.string.Countries_CôtedIvoire),
        Card("Croatia", R.string.Countries_Croatia),
        Card("Cuba", R.string.Countries_Cuba),
        Card("Cyprus", R.string.Countries_Cyprus),
        Card("Czech Republic", R.string.Countries_CzechRepublic),
        Card("Denmark", R.string.Countries_Denmark),
        Card("Djibouti", R.string.Countries_Djibouti),
        Card("Dominica", R.string.Countries_Dominica),
        Card("Dominican Republic", R.string.Countries_DominicanRepublic),
        Card("East Timor", R.string.Countries_EastTimor),
        Card("Ecuador", R.string.Countries_Ecuador),
        Card("Egypt", R.string.Countries_Egypt),
        Card("El Salvador", R.string.Countries_ElSalvador),
        Card("Equatorial Guinea", R.string.Countries_EquatorialGuinea),
        Card("Eritrea", R.string.Countries_Eritrea),
        Card("Estonia", R.string.Countries_Estonia),
        Card("Eswatini", R.string.Countries_Eswatini),
        Card("Ethiopia", R.string.Countries_Ethiopia),
        Card("Fiji", R.string.Countries_Fiji),
        Card("Finland", R.string.Countries_Finland),
        Card("Eswatini", R.string.Countries_Eswatini),
        Card("Ethiopia", R.string.Countries_Ethiopia),
        Card("Fiji", R.string.Countries_Fiji),
        Card("Finland", R.string.Countries_Finland),
        Card("France", R.string.Countries_France),
        Card("Gabon", R.string.Countries_Gabon),
        Card("Gambia", R.string.Countries_Gambia),
        Card("Georgia", R.string.Countries_Georgia),
        Card("Germany", R.string.Countries_Germany),
        Card("Ghana", R.string.Countries_Ghana),
        Card("Greece", R.string.Countries_Greece),
        Card("Grenada", R.string.Countries_Grenada),
        Card("Guatemala", R.string.Countries_Guatemala),
        Card("Guinea", R.string.Countries_Guinea),
        Card("GuineaBissau", R.string.Countries_GuineaBissau),
        Card("Guyana", R.string.Countries_Guyana),
        Card("Haiti", R.string.Countries_Haiti),
        Card("Honduras", R.string.Countries_Honduras),
        Card("Hungary", R.string.Countries_Hungary),
        Card("Iceland", R.string.Countries_Iceland),
        Card("India", R.string.Countries_India),
        Card("Indonesia", R.string.Countries_Indonesia),
        Card("Iran", R.string.Countries_Iran),
        Card("Iraq", R.string.Countries_Iraq),
        Card("Ireland", R.string.Countries_Ireland),
        Card("Israel", R.string.Countries_Israel),
        Card("Italy", R.string.Countries_Italy),
        Card("Jamaica", R.string.Countries_Jamaica),
        Card("Japan", R.string.Countries_Japan),
        Card("Jordan", R.string.Countries_Jordan),
        Card("Kazakhstan", R.string.Countries_Kazakhstan),
        Card("Kenya", R.string.Countries_Kenya)

















    )
}
