package abc.sadnoxx.hashtaggenerator.fragments.fonts

class StyledTextConverter {
    companion object {
        enum class StyleSet {
            MATHEMATICAL_BOLD_SCRIPT,
            SANS,
            SANS_BOLD,
            SANS_ITALIC,
            SANS_BOLD_ITALIC,
            MONOSPACE,
            FRAKTUR,
            BOLD_FRAKTUR,
            CIRCLED,
            CIRCLED_NEGATIVE,
            FULL_SQUARED,
            SQUARED,
            SCRIPT,
            DOUBLE_STRUCK,
            ASIAN,
            PARADISE,
            SUPERB
            // Add more style sets as needed
        }

        fun convertToStyledText(text: String, styleSet: StyleSet): String {
            val styledTextBuilder = StringBuilder()

            for (char in text) {
                val styledChar = getStyledCharacter(char, styleSet)
                styledTextBuilder.append(styledChar)
            }

            return styledTextBuilder.toString()
        }

        private fun getStyledCharacter(char: Char, styleSet: StyleSet): String {
            // Define your character styling logic here
            // Map the input character to its styled equivalent based on the selected style set

            return when (styleSet) {
                StyleSet.MATHEMATICAL_BOLD_SCRIPT -> getStyledCharacterSet1(char)
                StyleSet.SANS -> getStyledCharacterSet2(char)
                StyleSet.SANS_BOLD -> getStyledCharacterSet3(char)
                StyleSet.SANS_ITALIC -> getStyledCharacterSet4(char)
                StyleSet.SANS_BOLD_ITALIC -> getStyledCharacterSet5(char)
                StyleSet.MONOSPACE -> getStyledCharacterSet6(char)
                StyleSet.FRAKTUR -> getStyledCharacterSet7(char)
                StyleSet.BOLD_FRAKTUR -> getStyledCharacterSet8(char)
                StyleSet.CIRCLED -> getStyledCharacterSet9(char)
                StyleSet.CIRCLED_NEGATIVE -> getStyledCharacterSet10(char)
                StyleSet.FULL_SQUARED -> getStyledCharacterSet11(char)
                StyleSet.SQUARED -> getStyledCharacterSet12(char)
                StyleSet.SCRIPT -> getStyledCharacterSet13(char)
                StyleSet.DOUBLE_STRUCK -> getStyledCharacterSet14(char)
                StyleSet.ASIAN -> getStyledCharacterSet15(char)
                StyleSet.PARADISE -> getStyledCharacterSet16(char)
                StyleSet.SUPERB -> getStyledCharacterSet17(char)
                // Add more style sets and corresponding mapping functions as needed

            }
        }

        private fun getStyledCharacterSet1(char: Char): String {
            // Define mapping for style set 1

            return when (char) {
                '0' -> "\uD835\uDFEC"
                '1' -> "\uD835\uDFED"
                '2' -> "\uD835\uDFEE"
                '3' -> "\uD835\uDFEF"
                '4' -> "\uD835\uDFF0"
                '5' -> "\uD835\uDFF1"
                '6' -> "\uD835\uDFF2"
                '7' -> "\uD835\uDFF3"
                '8' -> "\uD835\uDFF4"
                '9' -> "\uD835\uDFF5"
                'A' -> "𝓐"
                'B' -> "𝓑"
                'C' -> "𝓒"
                'D' -> "𝓓"
                'E' -> "𝓔"
                'F' -> "𝓕"
                'G' -> "𝓖"
                'H' -> "𝓗"
                'I' -> "𝓘"
                'J' -> "𝓙"
                'K' -> "𝓚"
                'L' -> "𝓛"
                'M' -> "𝓜"
                'N' -> "𝓝"
                'O' -> "𝓞"
                'P' -> "𝓟"
                'Q' -> "𝓠"
                'R' -> "𝓡"
                'S' -> "𝓢"
                'T' -> "𝓣"
                'U' -> "𝓤"
                'V' -> "𝓥"
                'W' -> "𝓦"
                'X' -> "𝓧"
                'Y' -> "𝓨"
                'Z' -> "𝓩"
                'a' -> "𝓪"
                'b' -> "𝓫"
                'c' -> "𝓬"
                'd' -> "𝓭"
                'e' -> "𝓮"
                'f' -> "𝓯"
                'g' -> "𝓰"
                'h' -> "𝓱"
                'i' -> "𝓲"
                'j' -> "𝓳"
                'k' -> "𝓴"
                'l' -> "𝓵"
                'm' -> "𝓶"
                'n' -> "𝓷"
                'o' -> "𝓸"
                'p' -> "𝓹"
                'q' -> "𝓺"
                'r' -> "𝓻"
                's' -> "𝓼"
                't' -> "𝓽"
                'u' -> "𝓾"
                'v' -> "𝓿"
                'w' -> "𝔀"
                'x' -> "𝔁"
                'y' -> "𝔂"
                'z' -> "𝔃"
                // Add more character mappings for style set 1 as needed
                else -> char.toString() // Return the original character if no styling is available
            }
        }

        private fun getStyledCharacterSet2(char: Char): String {
            // Define mapping for style set 2

            return when (char) {
                '0' -> "\uD835\uDFE2"
                '1' -> "\uD835\uDFE3"
                '2' -> "\uD835\uDFE4"
                '3' -> "\uD835\uDFE5"
                '4' -> "\uD835\uDFE6"
                '5' -> "\uD835\uDFE7"
                '6' -> "\uD835\uDFE8"
                '7' -> "\uD835\uDFE9"
                '8' -> "\uD835\uDFEA"
                '9' -> "\uD835\uDFEB"
                'A' -> "\uD835\uDDA0"
                'B' -> "\uD835\uDDA1"
                'C' -> "\uD835\uDDA2"
                'D' -> "\uD835\uDDA3"
                'E' -> "\uD835\uDDA4"
                'F' -> "\uD835\uDDA5"
                'G' -> "\uD835\uDDA6"
                'H' -> "\uD835\uDDA7"
                'I' -> "\uD835\uDDA8"
                'J' -> "\uD835\uDDA9"
                'K' -> "\uD835\uDDAA"
                'L' -> "\uD835\uDDAB"
                'M' -> "\uD835\uDDAC"
                'N' -> "\uD835\uDDAD"
                'O' -> "\uD835\uDDAE"
                'P' -> "\uD835\uDDAF"
                'Q' -> "\uD835\uDDB0"
                'R' -> "\uD835\uDDB1"
                'S' -> "\uD835\uDDB2"
                'T' -> "\uD835\uDDB3"
                'U' -> "\uD835\uDDB4"
                'V' -> "\uD835\uDDB5"
                'W' -> "\uD835\uDDB6"
                'X' -> "\uD835\uDDB7"
                'Y' -> "\uD835\uDDB8"
                'Z' -> "\uD835\uDDB9"
                'a' -> "𝖺"
                'b' -> "𝖻"
                'c' -> "𝖼"
                'd' -> "𝖽"
                'e' -> "𝖾"
                'f' -> "𝖿"
                'g' -> "𝗀"
                'h' -> "𝗁"
                'i' -> "𝗂"
                'j' -> "𝗃"
                'k' -> "𝗄"
                'l' -> "𝗅"
                'm' -> "𝗆"
                'n' -> "𝗇"
                'o' -> "𝗈"
                'p' -> "𝗉"
                'q' -> "𝗊"
                'r' -> "𝗋"
                's' -> "𝗌"
                't' -> "𝗍"
                'u' -> "𝗎"
                'v' -> "𝗏"
                'w' -> "𝗐"
                'x' -> "𝗑"
                'y' -> "𝗒"
                'z' -> "𝗓"
                // Add more character mappings for style set 2 as needed
                else -> char.toString() // Return the original character if no styling is available
            }
        }

        private fun getStyledCharacterSet3(char: Char): String {
            // Define mapping for style set 1

            return when (char) {
                '0' -> "𝟬"
                '1' -> "𝟭"
                '2' -> "𝟮"
                '3' -> "𝟯"
                '4' -> "𝟰"
                '5' -> "𝟱"
                '6' -> "𝟲"
                '7' -> "𝟳"
                '8' -> "𝟴"
                '9' -> "𝟵"
                'A' -> "𝗔"
                'B' -> "𝗕"
                'C' -> "𝗖"
                'D' -> "𝗗"
                'E' -> "𝗘"
                'F' -> "𝗙"
                'G' -> "𝗚"
                'H' -> "𝗛"
                'I' -> "𝗜"
                'J' -> "𝗝"
                'K' -> "𝗞"
                'L' -> "𝗟"
                'M' -> "𝗠"
                'N' -> "𝗡"
                'O' -> "𝗢"
                'P' -> "𝗣"
                'Q' -> "𝗤"
                'R' -> "𝗥"
                'S' -> "𝗦"
                'T' -> "𝗧"
                'U' -> "𝗨"
                'V' -> "𝗩"
                'W' -> "𝗪"
                'X' -> "𝗫"
                'Y' -> "𝗬"
                'Z' -> "𝗭"
                'a' -> "𝗮"
                'b' -> "𝗯"
                'c' -> "𝗰"
                'd' -> "𝗱"
                'e' -> "𝗲"
                'f' -> "𝗳"
                'g' -> "𝗴"
                'h' -> "𝗵"
                'i' -> "𝗶"
                'j' -> "𝗷"
                'k' -> "𝗸"
                'l' -> "𝗹"
                'm' -> "𝗺"
                'n' -> "𝗻"
                'o' -> "𝗼"
                'p' -> "𝗽"
                'q' -> "𝗾"
                'r' -> "𝗿"
                's' -> "𝘀"
                't' -> "𝘁"
                'u' -> "𝘂"
                'v' -> "𝘃"
                'w' -> "𝘄"
                'x' -> "𝘅"
                'y' -> "𝘆"
                'z' -> "𝘇"
                // Add more character mappings for style set 1 as needed
                else -> char.toString() // Return the original character if no styling is available
            }
        }

        private fun getStyledCharacterSet4(char: Char): String {
            // Define mapping for style set 1

            return when (char) {
                '0' -> "𝟬"
                '1' -> "𝟭"
                '2' -> "𝟮"
                '3' -> "𝟯"
                '4' -> "𝟰"
                '5' -> "𝟱"
                '6' -> "𝟲"
                '7' -> "𝟳"
                '8' -> "𝟴"
                '9' -> "𝟵"
                'A' -> "𝘈"
                'B' -> "𝘉"
                'C' -> "𝘊"
                'D' -> "𝘋"
                'E' -> "𝘌"
                'F' -> "𝘍"
                'G' -> "𝘎"
                'H' -> "𝘏"
                'I' -> "𝘐"
                'J' -> "𝘑"
                'K' -> "𝘒"
                'L' -> "𝘓"
                'M' -> "𝘔"
                'N' -> "𝘕"
                'O' -> "𝘖"
                'P' -> "𝘗"
                'Q' -> "𝘘"
                'R' -> "𝘙"
                'S' -> "𝘚"
                'T' -> "𝘛"
                'U' -> "𝘜"
                'V' -> "𝘝"
                'W' -> "𝘞"
                'X' -> "𝘟"
                'Y' -> "𝘠"
                'Z' -> "𝘡"
                'a' -> "𝘢"
                'b' -> "𝘣"
                'c' -> "𝘤"
                'd' -> "𝘥"
                'e' -> "𝘦"
                'f' -> "𝘧"
                'g' -> "𝘨"
                'h' -> "𝘩"
                'i' -> "𝘪"
                'j' -> "𝘫"
                'k' -> "𝘬"
                'l' -> "𝘭"
                'm' -> "𝘮"
                'n' -> "𝘯"
                'o' -> "𝘰"
                'p' -> "𝘱"
                'q' -> "𝘲"
                'r' -> "𝘳"
                's' -> "𝘴"
                't' -> "𝘵"
                'u' -> "𝘶"
                'v' -> "𝘷"
                'w' -> "𝘸"
                'x' -> "𝘹"
                'y' -> "𝘺"
                'z' -> "𝘻"
                // Add more character mappings for style set 1 as needed
                else -> char.toString() // Return the original character if no styling is available
            }
        }

        private fun getStyledCharacterSet5(char: Char): String {
            // Define mapping for style set 1

            return when (char) {
                '0' -> "𝟬"
                '1' -> "𝟭"
                '2' -> "𝟮"
                '3' -> "𝟯"
                '4' -> "𝟰"
                '5' -> "𝟱"
                '6' -> "𝟲"
                '7' -> "𝟳"
                '8' -> "𝟴"
                '9' -> "𝟵"
                'A' -> "𝗔"
                'B' -> "𝗕"
                'C' -> "𝗖"
                'D' -> "𝗗"
                'E' -> "𝗘"
                'F' -> "𝗙"
                'G' -> "𝗚"
                'H' -> "𝗛"
                'I' -> "𝗜"
                'J' -> "𝗝"
                'K' -> "𝗞"
                'L' -> "𝗟"
                'M' -> "𝗠"
                'N' -> "𝗡"
                'O' -> "𝗢"
                'P' -> "𝗣"
                'Q' -> "𝗤"
                'R' -> "𝗥"
                'S' -> "𝗦"
                'T' -> "𝗧"
                'U' -> "𝗨"
                'V' -> "𝗩"
                'W' -> "𝗪"
                'X' -> "𝗫"
                'Y' -> "𝗬"
                'Z' -> "𝗭"
                'a' -> "𝗮"
                'b' -> "𝗯"
                'c' -> "𝗰"
                'd' -> "𝗱"
                'e' -> "𝗲"
                'f' -> "𝗳"
                'g' -> "𝗴"
                'h' -> "𝗵"
                'i' -> "𝗶"
                'j' -> "𝗷"
                'k' -> "𝗸"
                'l' -> "𝗹"
                'm' -> "𝗺"
                'n' -> "𝗻"
                'o' -> "𝗼"
                'p' -> "𝗽"
                'q' -> "𝗾"
                'r' -> "𝗿"
                's' -> "𝘀"
                't' -> "𝘁"
                'u' -> "𝘂"
                'v' -> "𝘃"
                'w' -> "𝘄"
                'x' -> "𝘅"
                'y' -> "𝘆"
                'z' -> "𝘇"
                // Add more character mappings for style set 1 as needed
                else -> char.toString() // Return the original character if no styling is available
            }
        }

        private fun getStyledCharacterSet6(char: Char): String {
            // Define mapping for style set 1

            return when (char) {
                '0' -> "𝟬"
                '1' -> "𝟭"
                '2' -> "𝟮"
                '3' -> "𝟯"
                '4' -> "𝟰"
                '5' -> "𝟱"
                '6' -> "𝟲"
                '7' -> "𝟳"
                '8' -> "𝟴"
                '9' -> "𝟵"
                'A' -> "𝙰"
                'B' -> "𝙱"
                'C' -> "𝙲"
                'D' -> "𝙳"
                'E' -> "𝙴"
                'F' -> "𝙵"
                'G' -> "𝙶"
                'H' -> "𝙷"
                'I' -> "𝙸"
                'J' -> "𝙹"
                'K' -> "𝙺"
                'L' -> "𝙻"
                'M' -> "𝙼"
                'N' -> "𝙽"
                'O' -> "𝙾"
                'P' -> "𝙿"
                'Q' -> "𝚀"
                'R' -> "𝚁"
                'S' -> "𝚂"
                'T' -> "𝚃"
                'U' -> "𝚄"
                'V' -> "𝚅"
                'W' -> "𝚆"
                'X' -> "𝚇"
                'Y' -> "𝚈"
                'Z' -> "𝚉"
                'a' -> "𝚊"
                'b' -> "𝚋"
                'c' -> "𝚌"
                'd' -> "𝚍"
                'e' -> "𝚎"
                'f' -> "𝚏"
                'g' -> "𝚐"
                'h' -> "𝚑"
                'i' -> "𝚒"
                'j' -> "𝚓"
                'k' -> "𝚔"
                'l' -> "𝚕"
                'm' -> "𝚖"
                'n' -> "𝚗"
                'o' -> "𝚘"
                'p' -> "𝚙"
                'q' -> "𝚚"
                'r' -> "𝚛"
                's' -> "𝚜"
                't' -> "𝚝"
                'u' -> "𝚞"
                'v' -> "𝚟"
                'w' -> "𝚠"
                'x' -> "𝚡"
                'y' -> "𝚢"
                'z' -> "𝚣"
                // Add more character mappings for style set 1 as needed
                else -> char.toString() // Return the original character if no styling is available
            }
        }

        private fun getStyledCharacterSet7(char: Char): String {
            // Define mapping for style set 1

            return when (char) {
                '0' -> "𝟬"
                '1' -> "𝟭"
                '2' -> "𝟮"
                '3' -> "𝟯"
                '4' -> "𝟰"
                '5' -> "𝟱"
                '6' -> "𝟲"
                '7' -> "𝟳"
                '8' -> "𝟴"
                '9' -> "𝟵"
                'A' -> "𝔄"
                'B' -> "𝔅"
                'C' -> "ℭ"
                'D' -> "𝔇"
                'E' -> "𝔈"
                'F' -> "𝔉"
                'G' -> "𝔊"
                'H' -> "ℌ"
                'I' -> "ℑ"
                'J' -> "𝔍"
                'K' -> "𝔎"
                'L' -> "𝔏"
                'M' -> "𝔐"
                'N' -> "𝔑"
                'O' -> "𝔒"
                'P' -> "𝔓"
                'Q' -> "𝔔"
                'R' -> "ℜ"
                'S' -> "𝔖"
                'T' -> "𝔗"
                'U' -> "𝔘"
                'V' -> "𝔙"
                'W' -> "𝔚"
                'X' -> "𝔛"
                'Y' -> "𝔜"
                'Z' -> "ℨ"
                'a' -> "𝔞"
                'b' -> "𝔟"
                'c' -> "𝔠"
                'd' -> "𝔡"
                'e' -> "𝔢"
                'f' -> "𝔣"
                'g' -> "𝔤"
                'h' -> "𝔥"
                'i' -> "𝔦"
                'j' -> "𝔧"
                'k' -> "𝔨"
                'l' -> "𝔩"
                'm' -> "𝔪"
                'n' -> "𝔫"
                'o' -> "𝔬"
                'p' -> "𝔭"
                'q' -> "𝔮"
                'r' -> "𝔯"
                's' -> "𝔰"
                't' -> "𝔱"
                'u' -> "𝔲"
                'v' -> "𝔳"
                'w' -> "𝔴"
                'x' -> "𝔵"
                'y' -> "𝔶"
                'z' -> "𝔷"
                // Add more character mappings for style set 1 as needed
                else -> char.toString() // Return the original character if no styling is available
            }
        }

        private fun getStyledCharacterSet8(char: Char): String {
            // Define mapping for style set 1

            return when (char) {
                '0' -> "𝟬"
                '1' -> "𝟭"
                '2' -> "𝟮"
                '3' -> "𝟯"
                '4' -> "𝟰"
                '5' -> "𝟱"
                '6' -> "𝟲"
                '7' -> "𝟳"
                '8' -> "𝟴"
                '9' -> "𝟵"
                'A' -> "𝕬"
                'B' -> "𝕭"
                'C' -> "𝕮"
                'D' -> "𝕯"
                'E' -> "𝕰"
                'F' -> "𝕱"
                'G' -> "𝕲"
                'H' -> "𝕳"
                'I' -> "𝕴"
                'J' -> "𝕵"
                'K' -> "𝕶"
                'L' -> "𝕷"
                'M' -> "𝕸"
                'N' -> "𝕹"
                'O' -> "𝕺"
                'P' -> "𝕻"
                'Q' -> "𝕼"
                'R' -> "𝕽"
                'S' -> "𝕾"
                'T' -> "𝕿"
                'U' -> "𝖀"
                'V' -> "𝖁"
                'W' -> "𝖂"
                'X' -> "𝖃"
                'Y' -> "𝖄"
                'Z' -> "𝖅"
                'a' -> "𝖆"
                'b' -> "𝖇"
                'c' -> "𝖈"
                'd' -> "𝖉"
                'e' -> "𝖊"
                'f' -> "𝖋"
                'g' -> "𝖌"
                'h' -> "𝖍"
                'i' -> "𝖎"
                'j' -> "𝖏"
                'k' -> "𝖐"
                'l' -> "𝖑"
                'm' -> "𝖒"
                'n' -> "𝖓"
                'o' -> "𝖔"
                'p' -> "𝖕"
                'q' -> "𝖖"
                'r' -> "𝖗"
                's' -> "𝖘"
                't' -> "𝖙"
                'u' -> "𝖚"
                'v' -> "𝖛"
                'w' -> "𝖜"
                'x' -> "𝖝"
                'y' -> "𝖞"
                'z' -> "𝖟"
                // Add more character mappings for style set 1 as needed
                else -> char.toString() // Return the original character if no styling is available
            }
        }

        private fun getStyledCharacterSet9(char: Char): String {
            // Define mapping for style set 1

            return when (char) {
                '0' -> "⓪"
                '1' -> "①"
                '2' -> "②"
                '3' -> "③"
                '4' -> "④"
                '5' -> "⑤"
                '6' -> "⑥"
                '7' -> "⑦"
                '8' -> "⑧"
                '9' -> "⑨"
                'A' -> "Ⓐ"
                'B' -> "Ⓑ"
                'C' -> "Ⓒ"
                'D' -> "Ⓓ"
                'E' -> "Ⓔ"
                'F' -> "Ⓕ"
                'G' -> "Ⓖ"
                'H' -> "Ⓗ"
                'I' -> "Ⓘ"
                'J' -> "Ⓙ"
                'K' -> "Ⓚ"
                'L' -> "Ⓛ"
                'M' -> "Ⓜ"
                'N' -> "Ⓝ"
                'O' -> "Ⓞ"
                'P' -> "Ⓟ"
                'Q' -> "Ⓠ"
                'R' -> "Ⓡ"
                'S' -> "Ⓢ"
                'T' -> "Ⓣ"
                'U' -> "Ⓤ"
                'V' -> "Ⓥ"
                'W' -> "Ⓦ"
                'X' -> "Ⓧ"
                'Y' -> "Ⓨ"
                'Z' -> "Ⓩ"
                'a' -> "ⓐ"
                'b' -> "ⓑ"
                'c' -> "ⓒ"
                'd' -> "ⓓ"
                'e' -> "ⓔ"
                'f' -> "ⓕ"
                'g' -> "ⓖ"
                'h' -> "ⓗ"
                'i' -> "ⓘ"
                'j' -> "ⓙ"
                'k' -> "ⓚ"
                'l' -> "ⓛ"
                'm' -> "ⓜ"
                'n' -> "ⓝ"
                'o' -> "ⓞ"
                'p' -> "ⓟ"
                'q' -> "ⓠ"
                'r' -> "ⓡ"
                's' -> "ⓢ"
                't' -> "ⓣ"
                'u' -> "ⓤ"
                'v' -> "ⓥ"
                'w' -> "ⓦ"
                'x' -> "ⓧ"
                'y' -> "ⓨ"
                'z' -> "ⓩ"
                // Add more character mappings for style set 1 as needed
                else -> char.toString() // Return the original character if no styling is available
            }
        }

        private fun getStyledCharacterSet10(char: Char): String {
            // Define mapping for style set 1

            return when (char) {
                '0' -> "⓿"
                '1' -> "❶"
                '2' -> "❷"
                '3' -> "❸"
                '4' -> "❹"
                '5' -> "❺"
                '6' -> "❻"
                '7' -> "❼"
                '8' -> "❽"
                '9' -> "❾"
                'A' -> "🅐"
                'B' -> "🅑"
                'C' -> "🅒"
                'D' -> "🅓"
                'E' -> "🅔"
                'F' -> "🅕"
                'G' -> "🅖"
                'H' -> "🅗"
                'I' -> "🅘"
                'J' -> "🅙"
                'K' -> "🅚"
                'L' -> "🅛"
                'M' -> "🅜"
                'N' -> "🅝"
                'O' -> "🅞"
                'P' -> "🅟"
                'Q' -> "🅠"
                'R' -> "🅡"
                'S' -> "🅢"
                'T' -> "🅣"
                'U' -> "🅤"
                'V' -> "🅥"
                'W' -> "🅦"
                'X' -> "🅧"
                'Y' -> "🅨"
                'Z' -> "🅩"
                'a' -> "🅐"
                'b' -> "🅑"
                'c' -> "🅒"
                'd' -> "🅓"
                'e' -> "🅔"
                'f' -> "🅕"
                'g' -> "🅖"
                'h' -> "🅗"
                'i' -> "🅘"
                'j' -> "🅙"
                'k' -> "🅚"
                'l' -> "🅛"
                'm' -> "🅜"
                'n' -> "🅝"
                'o' -> "🅞"
                'p' -> "🅟"
                'q' -> "🅠"
                'r' -> "🅡"
                's' -> "🅢"
                't' -> "🅣"
                'u' -> "🅤"
                'v' -> "🅥"
                'w' -> "🅦"
                'x' -> "🅧"
                'y' -> "🅨"
                'z' -> "🅩"
                // Add more character mappings for style set 1 as needed
                else -> char.toString() // Return the original character if no styling is available
            }
        }

        private fun getStyledCharacterSet11(char: Char): String {
            // Define mapping for style set 1

            return when (char) {
                '0' -> "0"
                '1' -> "1"
                '2' -> "2"
                '3' -> "3"
                '4' -> "4"
                '5' -> "5"
                '6' -> "6"
                '7' -> "7"
                '8' -> "8"
                '9' -> "9"
                'A' -> "🅰"
                'B' -> "🅱"
                'C' -> "🅲"
                'D' -> "🅳"
                'E' -> "🅴"
                'F' -> "🅵"
                'G' -> "🅶"
                'H' -> "🅷"
                'I' -> "🅸"
                'J' -> "🅹"
                'K' -> "🅺"
                'L' -> "🅻"
                'M' -> "🅼"
                'N' -> "🅽"
                'O' -> "🅾"
                'P' -> "🅿"
                'Q' -> "🆀"
                'R' -> "🆁"
                'S' -> "🆂"
                'T' -> "🆃"
                'U' -> "🆄"
                'V' -> "🆅"
                'W' -> "🆆"
                'X' -> "🆇"
                'Y' -> "🆈"
                'Z' -> "🆉"
                'a' -> "🅰"
                'b' -> "🅱"
                'c' -> "🅲"
                'd' -> "🅳"
                'e' -> "🅴"
                'f' -> "🅵"
                'g' -> "🅶"
                'h' -> "🅷"
                'i' -> "🅸"
                'j' -> "🅹"
                'k' -> "🅺"
                'l' -> "🅻"
                'm' -> "🅼"
                'n' -> "🅽"
                'o' -> "🅾"
                'p' -> "🅿"
                'q' -> "🆀"
                'r' -> "🆁"
                's' -> "🆂"
                't' -> "🆃"
                'u' -> "🆄"
                'v' -> "🆅"
                'w' -> "🆆"
                'x' -> "🆇"
                'y' -> "🆈"
                'z' -> "🆉"
                // Add more character mappings for style set 1 as needed
                else -> char.toString() // Return the original character if no styling is available
            }
        }

        private fun getStyledCharacterSet12(char: Char): String {
            // Define mapping for style set 1

            return when (char) {
                '0' -> "0"
                '1' -> "1"
                '2' -> "2"
                '3' -> "3"
                '4' -> "4"
                '5' -> "5"
                '6' -> "6"
                '7' -> "7"
                '8' -> "8"
                '9' -> "9"
                'A' -> "🄰"
                'B' -> "🄱"
                'C' -> "🄲"
                'D' -> "🄳"
                'E' -> "🄴"
                'F' -> "🄵"
                'G' -> "🄶"
                'H' -> "🄷"
                'I' -> "🄸"
                'J' -> "🄹"
                'K' -> "🄺"
                'L' -> "🄻"
                'M' -> "🄼"
                'N' -> "🄽"
                'O' -> "🄾"
                'P' -> "🄿"
                'Q' -> "🅀"
                'R' -> "🅁"
                'S' -> "🅂"
                'T' -> "🅃"
                'U' -> "🅄"
                'V' -> "🅅"
                'W' -> "🅆"
                'X' -> "🅇"
                'Y' -> "🅈"
                'Z' -> "🅉"
                'a' -> "🄰"
                'b' -> "🄱"
                'c' -> "🄲"
                'd' -> "🄳"
                'e' -> "🄴"
                'f' -> "🄵"
                'g' -> "🄶"
                'h' -> "🄷"
                'i' -> "🄸"
                'j' -> "🄹"
                'k' -> "🄺"
                'l' -> "🄻"
                'm' -> "🄼"
                'n' -> "🄽"
                'o' -> "🄾"
                'p' -> "🄿"
                'q' -> "🅀"
                'r' -> "🅁"
                's' -> "🅂"
                't' -> "🅃"
                'u' -> "🅄"
                'v' -> "🅅"
                'w' -> "🅆"
                'x' -> "🅇"
                'y' -> "🅈"
                'z' -> "🅉"
                // Add more character mappings for style set 1 as needed
                else -> char.toString() // Return the original character if no styling is available
            }
        }

        private fun getStyledCharacterSet13(char: Char): String {
            // Define mapping for style set 1

            return when (char) {
                '0' -> "0"
                '1' -> "1"
                '2' -> "2"
                '3' -> "3"
                '4' -> "4"
                '5' -> "5"
                '6' -> "6"
                '7' -> "7"
                '8' -> "8"
                '9' -> "9"
                'A' -> "𝒜"
                'B' -> "ℬ"
                'C' -> "𝒞"
                'D' -> "𝒟"
                'E' -> "ℰ"
                'F' -> "ℱ"
                'G' -> "𝒢"
                'H' -> "ℋ"
                'I' -> "ℐ"
                'J' -> "𝒥"
                'K' -> "𝒦"
                'L' -> "ℒ"
                'M' -> "ℳ"
                'N' -> "𝒩"
                'O' -> "𝒪"
                'P' -> "𝒫"
                'Q' -> "𝒬"
                'R' -> "ℛ"
                'S' -> "𝒮"
                'T' -> "𝒯"
                'U' -> "𝒰"
                'V' -> "𝒱"
                'W' -> "𝒲"
                'X' -> "𝒳"
                'Y' -> "𝒴"
                'Z' -> "𝒵"
                'a' -> "𝒶"
                'b' -> "𝒷"
                'c' -> "𝒸"
                'd' -> "𝒹"
                'e' -> "ℯ"
                'f' -> "𝒻"
                'g' -> "ℊ"
                'h' -> "𝒽"
                'i' -> "𝒾"
                'j' -> "𝒿"
                'k' -> "𝓀"
                'l' -> "𝓁"
                'm' -> "𝓂"
                'n' -> "𝓃"
                'o' -> "ℴ"
                'p' -> "𝓅"
                'q' -> "𝓆"
                'r' -> "𝓇"
                's' -> "𝓈"
                't' -> "𝓉"
                'u' -> "𝓊"
                'v' -> "𝓋"
                'w' -> "𝓌"
                'x' -> "𝓍"
                'y' -> "𝓎"
                'z' -> "𝓏"
                // Add more character mappings for style set 1 as needed
                else -> char.toString() // Return the original character if no styling is available
            }
        }

        private fun getStyledCharacterSet14(char: Char): String {
            // Define mapping for style set 1

            return when (char) {
                '0' -> "𝟘"
                '1' -> "𝟙"
                '2' -> "𝟚"
                '3' -> "𝟛"
                '4' -> "𝟜"
                '5' -> "𝟝"
                '6' -> "𝟞"
                '7' -> "𝟟"
                '8' -> "𝟠"
                '9' -> "𝟡"
                'A' -> "𝔸"
                'B' -> "𝔹"
                'C' -> "ℂ"
                'D' -> "𝔻"
                'E' -> "𝔼"
                'F' -> "𝔽"
                'G' -> "𝔾"
                'H' -> "ℍ"
                'I' -> "𝕀"
                'J' -> "𝕁"
                'K' -> "𝕂"
                'L' -> "𝕃"
                'M' -> "𝕄"
                'N' -> "ℕ"
                'O' -> "𝕆"
                'P' -> "ℙ"
                'Q' -> "ℚ"
                'R' -> "ℝ"
                'S' -> "𝕊"
                'T' -> "𝕋"
                'U' -> "𝕌"
                'V' -> "𝕍"
                'W' -> "𝕎"
                'X' -> "𝕏"
                'Y' -> "𝕐"
                'Z' -> "ℤ"
                'a' -> "𝕒"
                'b' -> "𝕓"
                'c' -> "𝕔"
                'd' -> "𝕕"
                'e' -> "𝕖"
                'f' -> "𝕗"
                'g' -> "𝕘"
                'h' -> "𝕙"
                'i' -> "𝕚"
                'j' -> "𝕛"
                'k' -> "𝕜"
                'l' -> "𝕝"
                'm' -> "𝕞"
                'n' -> "𝕟"
                'o' -> "𝕠"
                'p' -> "𝕡"
                'q' -> "𝕢"
                'r' -> "𝕣"
                's' -> "𝕤"
                't' -> "𝕥"
                'u' -> "𝕦"
                'v' -> "𝕧"
                'w' -> "𝕨"
                'x' -> "𝕩"
                'y' -> "𝕪"
                'z' -> "𝕫"
                // Add more character mappings for style set 1 as needed
                else -> char.toString() // Return the original character if no styling is available
            }
        }

        private fun getStyledCharacterSet15(char: Char): String {
            // Define mapping for style set 1

            return when (char) {
                '0' -> "0"
                '1' -> "1"
                '2' -> "2"
                '3' -> "3"
                '4' -> "4"
                '5' -> "5"
                '6' -> "6"
                '7' -> "7"
                '8' -> "8"
                '9' -> "9"
                'A' -> "卂"
                'B' -> "乃"
                'C' -> "匚"
                'D' -> "ᗪ"
                'E' -> "乇"
                'F' -> "千"
                'G' -> "Ꮆ"
                'H' -> "卄"
                'I' -> "丨"
                'J' -> "ﾌ"
                'K' -> "Ҝ"
                'L' -> "ㄥ"
                'M' -> "爪"
                'N' -> "几"
                'O' -> "ㄖ"
                'P' -> "卩"
                'Q' -> "Ɋ"
                'R' -> "尺"
                'S' -> "丂"
                'T' -> "ㄒ"
                'U' -> "ㄩ"
                'V' -> "ᐯ"
                'W' -> "山"
                'X' -> "乂"
                'Y' -> "ㄚ"
                'Z' -> "乙"
                'a' -> "卂"
                'b' -> "乃"
                'c' -> "匚"
                'd' -> "ᗪ"
                'e' -> "乇"
                'f' -> "千"
                'g' -> "Ꮆ"
                'h' -> "卄"
                'i' -> "丨"
                'j' -> "ﾌ"
                'k' -> "Ҝ"
                'l' -> "ㄥ"
                'm' -> "爪"
                'n' -> "几"
                'o' -> "ㄖ"
                'p' -> "卩"
                'q' -> "Ɋ"
                'r' -> "尺"
                's' -> "丂"
                't' -> "ㄒ"
                'u' -> "ㄩ"
                'v' -> "ᐯ"
                'w' -> "山"
                'x' -> "乂"
                'y' -> "ㄚ"
                'z' -> "乙"
                // Add more character mappings for style set 1 as needed
                else -> char.toString() // Return the original character if no styling is available
            }

        }

        private fun getStyledCharacterSet16(char: Char): String {
            // Define mapping for style set 1

            return when (char) {
                '0' -> "0"
                '1' -> "1"
                '2' -> "2"
                '3' -> "3"
                '4' -> "4"
                '5' -> "5"
                '6' -> "6"
                '7' -> "7"
                '8' -> "8"
                '9' -> "9"
                'A' -> "Ꮧ"
                'B' -> "Ᏸ"
                'C' -> "ፈ"
                'D' -> "Ꮄ"
                'E' -> "Ꮛ"
                'F' -> "Ꭶ"
                'G' -> "Ꮆ"
                'H' -> "Ꮒ"
                'I' -> "Ꭵ"
                'J' -> "Ꮰ"
                'K' -> "Ꮶ"
                'L' -> "Ꮭ"
                'M' -> "Ꮇ"
                'N' -> "Ꮑ"
                'O' -> "Ꭷ"
                'P' -> "Ꭾ"
                'Q' -> "Ꭴ"
                'R' -> "Ꮢ"
                'S' -> "Ꮥ"
                'T' -> "Ꮦ"
                'U' -> "Ꮼ"
                'V' -> "Ꮙ"
                'W' -> "Ꮗ"
                'X' -> "ጀ"
                'Y' -> "Ꭹ"
                'Z' -> "ፚ"
                'a' -> "Ꮧ"
                'b' -> "Ᏸ"
                'c' -> "ፈ"
                'd' -> "Ꮄ"
                'e' -> "Ꮛ"
                'f' -> "Ꭶ"
                'g' -> "Ꮆ"
                'h' -> "Ꮒ"
                'i' -> "Ꭵ"
                'j' -> "Ꮰ"
                'k' -> "Ꮶ"
                'l' -> "Ꮭ"
                'm' -> "Ꮇ"
                'n' -> "Ꮑ"
                'o' -> "Ꭷ"
                'p' -> "Ꭾ"
                'q' -> "Ꭴ"
                'r' -> "Ꮢ"
                's' -> "Ꮥ"
                't' -> "Ꮦ"
                'u' -> "Ꮼ"
                'v' -> "Ꮙ"
                'w' -> "Ꮗ"
                'x' -> "ጀ"
                'y' -> "Ꭹ"
                'z' -> "ፚ"
                // Add more character mappings for style set 1 as needed
                else -> char.toString() // Return the original character if no styling is available
            }

        }
        private fun getStyledCharacterSet17(char: Char): String {
            // Define mapping for style set 1

            return when (char) {
                '0' -> "0"
                '1' -> "1"
                '2' -> "2"
                '3' -> "3"
                '4' -> "4"
                '5' -> "5"
                '6' -> "6"
                '7' -> "7"
                '8' -> "8"
                '9' -> "9"
                'A' -> "ค"
                'B' -> "๖"
                'C' -> "¢"
                'D' -> "໓"
                'E' -> "ē"
                'F' -> "f"
                'G' -> "ງ"
                'H' -> "h"
                'I' -> "i"
                'J' -> "ว"
                'K' -> "k"
                'L' -> "l"
                'M' -> "๓"
                'N' -> "ຖ"
                'O' -> "໐"
                'P' -> "p"
                'Q' -> "๑"
                'R' -> "r"
                'S' -> "Ş"
                'T' -> "t"
                'U' -> "น"
                'V' -> "ง"
                'W' -> "ຟ"
                'X' -> "x"
                'Y' -> "ฯ"
                'Z' -> "ຊ"
                'a' -> "ค"
                'b' -> "๖"
                'c' -> "¢"
                'd' -> "໓"
                'e' -> "ē"
                'f' -> "f"
                'g' -> "ງ"
                'h' -> "h"
                'i' -> "i"
                'j' -> "ว"
                'k' -> "k"
                'l' -> "l"
                'm' -> "๓"
                'n' -> "ຖ"
                'o' -> "໐"
                'p' -> "p"
                'q' -> "๑"
                'r' -> "r"
                's' -> "Ş"
                't' -> "t"
                'u' -> "น"
                'v' -> "ง"
                'w' -> "ຟ"
                'x' -> "x"
                'y' -> "ฯ"
                'z' -> "ຊ"

                // Add more character mappings for style set 1 as needed
                else -> char.toString() // Return the original character if no styling is available
            }

        }

    }
}
